### ISSUE TITLE
Add support for bgpmon.io

### ISSUE THREAD

**Issue by pgigis** [FORTH-ICS-INSPIRE/artemis#104]
**Describe the solution you'd like**
Bgpmon.io is online again (https://www.bgpmon.io/join-the-peering.html)

Check this: https://github.com/CSUNetSec/bgpmon

**Comment by vkotronis** [comment]
please check also our initial deprecated code:
https://github.com/FORTH-ICS-INSPIRE/artemis/commit/3365b2d2e1a238d3ace9f0982d855010970d2d51

**Comment by vkotronis** [comment]
Current status: @pgigis to send email to bgpmon developers to ask what is the best way to integrate their client in the ARTEMIS taps set.

**Comment by slowr** [comment]
@pgigis do we have an update on this?

It seems that the project is not touched since february.

**Comment by slowr** [comment]
bgpmon.io seems to be inactive. closing for now
