### ISSUE TITLE
Support Active Directory integration for user authentication

### ISSUE THREAD

**Issue by stkonst** [FORTH-ICS-INSPIRE/artemis#108]
The idea is to integrate Artemis with Active Directory authentication system and potentially LDAP which is more open source. Thus, when a user inserts his credentials the GUI will authenticate the user against an Active Directory server and will assign him the appropriate role (admin or simple user). 

If you have more questions on that we can discuss it.

**Comment by vkotronis** [comment]
Related to https://github.com/FORTH-ICS-INSPIRE/artemis/pull/105

**Comment by pixitha** [comment]
Please include support for LDAPS as part of this, and/or LDAP+StartTLS.
