### ISSUE TITLE
Load avg of server host shown in System Status frame

### ISSUE THREAD

**Issue by pixitha** [FORTH-ICS-INSPIRE/artemis#109]
**Is your feature request related to a problem? Please describe.**
It would be nice to see some quick overall system load info on the main overview page, that way you can get a feel for if everything is running ok on the underlying host.

**Describe the solution you'd like**
Even a simple txt line after the Module status with the normal 5/10/15 load avg info and maybe memory.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by vkotronis** [comment]
Moving to https://github.com/FORTH-ICS-INSPIRE/artemis/issues/112 (duplicate) and adding @pixitha 's comment there.
