### ISSUE TITLE
Container/reporter for reporting host utilization statistics

### ISSUE THREAD

**Issue by vkotronis** [FORTH-ICS-INSPIRE/artemis#112]
**Is your feature request related to a problem? Please describe.**
Reporting host utilization statistics (CPU, RAM, etc.).
It would be nice to see some quick overall system load info on the main overview page, that way you can get a feel for if everything is running ok on the underlying host.

**Describe the solution you'd like**
Exhibit such information e.g., in ARTEMIS page footer (overview).
Even a simple txt line after the Module status with the normal 5/10/15 load avg info and maybe memory.
To do this:
1. use an available or custom reporting container, instructing it to report stats let's say every second
2. connect it with rabbitmq
3. instruct it to send messages to the db
4. the db will store them in a "host_stats" table
5. the frontend will use graphql to access these statistics

Ideally we would need:
CPU, RAM and DISK for the host machine, and CPU and RAM per container (e.g., backend, postgres) and per module (e.g., backend monitor, etc.).

Per-module stats could be placed in the overview table upper right, host-wide stats at the bottom of the page, and per-container stats are optional (maybe they need their own page).

We need a **lightweight** solution!

**Describe alternatives you've considered**
https://github.com/google/cadvisor (BUT: high CPU usage!)
https://github.com/stefanprodan/dockprom (BUT: too much info, heavy)
https://github.com/pitrho/docker-host-stats (sth along these veins...)

**Additional context**
https://github.com/pitrho/docker-host-stats
if you run:
```
docker run -v=/proc:/proc_host:ro pitrho/docker-host-stats -cdmn -f 1
```
you get every second:
```
{"message": "Reporting stats using cAdvisor: False", "host-stats": {"disk": {"/": {"status": "OK", "total": 486.62, "percent": 86.2, "free": 42.46, "used": 419.42}}, "network": {"status": "OK", "interfaces": {"allnic": {"packets_sent": 9, "packets_recv": 11, "bytes_recv": 1012, "dropout": 0, "bytes_sent": 572, "errout": 0, "errin": 0, "dropin": 0}}}, "hostname": "ac001afb8312", "cpu": {"status": "OK", "percent_combined": 28.4, "percent_per_cpu": [52.4, 15.8, 15.8, 15.8]}, "memory": {"available": 7.7, "status": "OK", "used": 15.17, "percent": 53.9, "free": 1.54, "total": 16.7}}}
```
This dictionary can be sent to the db via rabbitmq and update a table row every second.

**Comment by pgigis** [comment]
This functionality is provided by other monitoring tools which are supposed to co-exist with ARTEMIS. (kubernetes, nagios, etc.)

**Comment by pgigis** [comment]
After internal discussion we decided that the proposed functionality can be provided by other monitoring tools which are supposed to co-exist with ARTEMIS. (kubernetes, nagios, etc.)
