### ISSUE TITLE
Next to ARTEMIS version on frontend, output also the database version

### ISSUE THREAD

**Issue by vkotronis** [FORTH-ICS-INSPIRE/artemis#115]
**Is your feature request related to a problem? Please describe.**
It is useful to also know the exact database version on which ARTEMIS runs (**NOT the .env variable but the actual version underneath!**).
Also put quotes next to the ARTEMIS and db versions.

**Describe the solution you'd like**
```
ARTEMIS version 'release-1.1.0' | DB version '9'
```
so:
```
ARTEMIS version '<SYSTEM_VERSION>' | DB version '<VERSION_QUERIED_FROM_DB>'
```

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by slowr** [comment]
so in case of latest it will say ARTEMIS 'latest' (database 'v9')?
Maybe make it something like ARTEMIS version X | DB version Y

**Comment by vkotronis** [comment]
> so in case of latest it will say ARTEMIS 'latest' (database 'v9')?
> Maybe make it something like ARTEMIS version X | DB version Y

@slowr I updated the comment according to your recommendation
