### ISSUE TITLE
Do not break down rfc2622 prefixes in configuration, but in each module

### ISSUE THREAD

**Issue by vkotronis** [FORTH-ICS-INSPIRE/artemis#122]
**Is your feature request related to a problem? Please describe.**
Currently rfc2622 prefixes are broken down in the configuration, inducing considerable delays.

**Describe the solution you'd like**
This should be done at the stage of each module (prefix tree compilation).

ATTENTION: In the frontend, we should display the rfc2622-configured prefixes as they are (not broken down visually). Hijack prefix matches etc. can occur as till now.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by pixitha** [comment]
Current code with a config like this: `2400:2000::/32^48` breaks the frontend, due to timeout or memory issues.

Smaller aggregates work fine however, like `::/47^48` so anything that can more simply manage the prefixes besides printing the whole list should work better.
