### ISSUE TITLE
Fix frontend actions logic

### ISSUE THREAD

**Issue by slowr** [FORTH-ICS-INSPIRE/artemis#131]
**Describe the bug**
Each action connects to the rabbitmq server in the constructor but if it fails it will continue as nothing happened

**Affected Component(s)**
- [ ] Back-End (Database, Microservices, Containers, etc)
- [x] Front-End (Flask, API, etc)
- [ ] Docs
- [ ] Build System

**To Reproduce**

**Expected behavior**
Return a failed to connect to the rabbitmq server message to inform the user

**Screenshots**

**System (please complete the following information):**

**Additional context**

**Comment by slowr** [comment]
You should initialize the connection where you use it with the `with` operator. Right now we may have an exception but we will continue without caring..
```
        self.init_conn()
        self.hijack_exchange = Exchange(
            "hijack-update", type="direct", durable=False, delivery_mode=1
        )

    def init_conn(self):
        try:
            self.connection = Connection(RABBITMQ_URI)
        except BaseException:
            log.exception("Resolve_hijack failed to connect to rabbitmq.")
```

**Comment by slowr** [comment]
they can even be static functions and not classes because they are stateless either way

**Comment by pgigis** [comment]
Closed by https://github.com/FORTH-ICS-INSPIRE/artemis/pull/162
