### ISSUE TITLE
Total number of routes monitored counter

### ISSUE THREAD

**Issue by pixitha** [FORTH-ICS-INSPIRE/artemis#139]
**Is your feature request related to a problem? Please describe.**
It would be nice to see a number in the stats field showing the actual number of prefixes being monitored.

**Describe the solution you'd like**
Counter should include the total number of unique routes that are being monitored, so if your using /16^24 it would count all the 24s, not just the supernet.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by vkotronis** [comment]
@slowr we can get this by imittating the monitoring module functionality, is that correct?
```
            # only keep super prefixes for monitors
            for prefix in self.prefix_tree.prefixes(): 
               self.prefixes.add(self.prefix_tree.search_worst(prefix).prefix)
```
and so on.
