### ISSUE TITLE
Check that RIPEstat comply with data api and check the addition of abuse emails to ASN info

### ISSUE THREAD

**Issue by vkotronis** [FORTH-ICS-INSPIRE/artemis#164]
**Is your feature request related to a problem? Please describe.**
Currently the user needs to manually search for email contact information when investigating a hijack.
Also we are using calls of type: 
```
https://stat.ripe.net/data/as-names/data.json?resource=AS' + ASN
https://stat.ripe.net/data/geoloc/data.json?resource=AS' + ASN
```
Check if these are properly compliant with the data API: https://stat.ripe.net/docs/data_api

**Describe the solution you'd like**
Use data API and add abuse email information (check how to retrieve it).
https://stat.ripe.net/docs/data_api#abuse-contact-finder

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by pgigis** [comment]
Closed by #165
