### ISSUE TITLE
Create ARTEMIS logo

### ISSUE THREAD

**Issue by vkotronis** [FORTH-ICS-INSPIRE/artemis#169]
**Is your feature request related to a problem? Please describe.**
We need a high-quality logo (proper version + thumbnail)

**Describe the solution you'd like**
ARTEMIS logo

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by albertocaida** [comment]
Sorry, this was blocked on me assigning the task to our graphic design intern. We just hired a new intern and (s)he is going to work on an Artemis logo. Hopefully we should have some concept designs within the next week

**Comment by pgigis** [comment]
I also created the following text-logo
![atemis_text_logo](https://user-images.githubusercontent.com/8319353/56343975-f1386500-61c4-11e9-886d-373f2516735a.png)
