### ISSUE TITLE
Extend Artemis to support AS-SET 

### ISSUE THREAD

**Issue by stkonst** [FORTH-ICS-INSPIRE/artemis#176]
Instead of configuring big lists of  BGP peers (AS numbers), we could extend Artemis to read an AS-SET and then go to IRR database (e.g. RIPE) and retrieve from there the list of AS numbers. Some big networks have some automation around IRR databases to keep their AS-SETs up-to-date, so we could re-use this information.

**Comment by vkotronis** [comment]
Some resources for querying to help with this issue (please check only relevant ones):
https://www.ripe.net/manage-ips-and-asns/db/support/querying-the-ripe-database
https://github.com/RIPE-NCC/whois/wiki/WHOIS-REST-API
https://github.com/RIPE-NCC/whois/wiki/WHOIS-REST-API-WhoisResources
https://stat.ripe.net/docs/data_api

Also, we need to investigate if we can generalize this beyond the RIPE NCC IRR, to other IRRs via a
proper abstraction interface and tool (e.g., whois).

@stkonst could you please provide an example of an AS-SET that is publicly available and searchable in the RIPE DB? To get an idea on the format, etc. Also ideas on making this generic are most welcome.

**Comment by stkonst** [comment]
Sure, an example of a AS-SET is the following: "AS-AMS-IX-PEERS"

if you do "whois" you will get the object and then you can extract the members easily, for example:
stkonst@ssh:~$ whois AS-AMS-IX-PEERS | grep members | awk '{ print $2 }'
AS42
AS112
AS286
AS702
AS714
AS855
AS1101
AS1103
....

**Comment by vkotronis** [comment]
So the most relevant approach would be either using the RIPE's WHOIS REST iface:
https://github.com/RIPE-NCC/whois/wiki/WHOIS-REST-API
or generalize more and leverage whois python tools, for querying generic IRR objects (or build our own parser).

**Comment by vkotronis** [comment]
@pgigis I am assigning this to you since you have more experience with the RIPE NCC tools. Let's discuss if we can make the new feature more generic (e.g., including whois AS-SETs etc.).

**Comment by vkotronis** [comment]
@pgigis after discussion, the corresponding variables should be prefixed by the user by e.g., "RIPE_..." so that the configurator knows what API to use for querying. Everything on the backend's side will take place in configuration.py (if a variable with this prefix is encountered, then the corresponding list is created after the query; if the query fails, then an error message is returned to the frontend). Regarding the periodic re-check, you can simply add a button in the configuration webpage stating "Update Variables", which will essentially resend the configuration to the backend for re-checking.

**Comment by vkotronis** [comment]
The AS-SETs resolved by RIPE should start with: RIPE_ASSET_.... (so you can use a regex to know what to resolve). In the end this should be resolved to nothing more than a classic ARTEMIS AS list (the anchor logic will be similar to the rest, only the content within will be translated). I do not think we have to do the translation each time at each module (like we do with RFC2622 prefixes for scalabaility reasons; in the AS-SET instance we have to query the RIPE interface, which is better done once upon reconfiguration). If the resolution cannot be done, we need to throw an error in configuration in the UI (sth like: AS-SET sth could not be resolved).
