### ISSUE TITLE
Ensure automatic ARTEMIS recovery upon physical server reboot

### ISSUE THREAD

**Issue by vkotronis** [FORTH-ICS-INSPIRE/artemis#192]
**Is your feature request related to a problem? Please describe.**
When the server running ARTEMIS is reboot, ARTEMIS should properly recover at its previous stage (maybe by defaulting to monitor, detect and mitigate services to "OFF" as normal, but in any case being able to run without any issues).

**Describe the solution you'd like**
Automatic recovery without the user needing to restart docker-compose.

**Describe alternatives you've considered**
N/A

**Additional context**
https://forums.docker.com/t/how-to-handle-server-reboot-when-using-docker-compose/26374

Connected with #231 (regarding module reset).

**Comment by vkotronis** [comment]
This requires investigation also of what actually hangs or malfunction in case the server reboots
(if you get this assigned, please try with a VM that you can reset quickly for testing).

**Comment by vkotronis** [comment]
Btw, if we do a 
```
docker-compose restart
```
instead of a 
```
docker-compose down
docker-compose up -d
```
nginx needs explicit restarting for some reason (it should restart last so that it has the locations of the others, probably the network is not established yet upon restart?)

**Comment by vkotronis** [comment]
This is also useful in this context (ensure certain restart order): https://www.reddit.com/r/docker/comments/81azit/starting_containers_in_specific_order_after_reboot/

https://docs.docker.com/compose/startup-order/

Essentially we want nginx to restart after everything has restarted so that it can find the new IPs. Startup works perfectly with "depends_on"; however restarts and reboots induce this problem since nginx does not know the IP address of the restarted service...

**Comment by vkotronis** [comment]
Moving to 1.4.0 release, not critical for current or new users.

**Comment by smith8917** [comment]
successfully tested "restart: always" in every docker stanza in docker-compose.yaml.  We also have the monitor and detection modules set to enable automatically once the app is running
