### ISSUE TITLE
Replace initContainer for waiting with readinessProbe

### ISSUE THREAD

**Issue by slowr** [FORTH-ICS-INSPIRE/artemis#208]
**Is your feature request related to a problem? Please describe.**
Right now the containers are sleeping until the database and rabbitmq ports are up by a script that constantly checks the endpoints. We can replace this by using the `readinessProbe` feature. 

Material:
https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/
https://stackoverflow.com/questions/55423405/k8s-livenessprobe-vs-readinessprobe

**Comment by vkotronis** [comment]
@slowr is this easy to implement? Should I keep it in 1.4.0 or migrate it?

**Comment by slowr** [comment]
this issue is irrelevant now, I am closing it
