### ISSUE TITLE
Documentation fix on enabling additional services

### ISSUE THREAD

**Issue by leopoul** [FORTH-ICS-INSPIRE/artemis#21]
**Describe the bug**
Documentation - https://github.com/FORTH-ICS-INSPIRE/artemis/wiki#starting-artemis - mentions:
...
or if you want additional services:
`docker-compose -f docker.compose.yaml -f docker_compose.<extra_service>.yaml up -d`
...
It should be:
or if you want additional services:
`docker-compose -f docker-compose.yaml -f docker-compose.<extra_service>.yaml up -d`

* docker.compose.yaml => docker-compose.yaml
* docker_compose.<extra_service>.yaml => docker-compose.<extra_service>.yaml

**Affected Component(s)**
- [ ] Back-End (Database, Microservices, Containers, etc)
- [ ] Front-End (Flask, API, etc)
- [X] Docs
- [ ] Build System

**To Reproduce**
1. Try to enable grafana: `docker-compose -f docker.compose.yaml -f docker_compose.grafana.yaml up -d`
2. Error: `ERROR: .FileNotFoundError: [Errno 2] No such file or directory: './docker.compose.yaml'`
3. Fix docker.compose.yaml to : `docker-compose -f docker-compose.yaml -f docker_compose.grafana.yaml up -d`
4. Error: `ERROR: .FileNotFoundError: [Errno 2] No such file or directory: './docker_compose.grafana.yaml'`
5. Fix: `docker-compose -f docker-compose.yaml -f docker-compose.grafana.yaml up -d`

**Expected behavior**
No error when running command for additional services

**Screenshots**
N/A

**System (please complete the following information):**
 - OS: Centos 7
 - Version: Artemis 1.0.0

**Additional context**
N/A

**Comment by vkotronis** [comment]
Fixed directly in the wiki https://github.com/FORTH-ICS-INSPIRE/artemis/wiki. 
@leopoul Thanks for catching this!

Closing issue.
