### ISSUE TITLE
Refactor complex methods for codefactor

### ISSUE THREAD

**Issue by vkotronis** [FORTH-ICS-INSPIRE/artemis#215]
**Describe the bug**
https://www.codefactor.io/repository/github/forth-ics-inspire/artemis/pull/213

**Affected Component(s)**
- [X] Back-End (Database, Microservices, Containers, etc)
- [ ] Front-End (Flask, API, etc)
- [ ] Docs
- [ ] Build System

**Additional context**
Refactoring will require careful testing of the changes.

[Severity: Minor] Complex Method complexity = 18
Found in monitor\core\utils\__init__.py:274-377
```
def translate_rfc2622(input_prefix, just_match=False):
```

[Severity: Minor] Complex Method complexity = 17
Found in monitor\core\taps\ripe_ris.py:113-185
```
def parse_ripe_ris(connection, prefixes_file, hosts):
```

[Severity: Minor] Complex Method complexity = 31
Found in monitor\core\taps\ripe_ris.py:29-110
```
def normalize_ripe_ris(msg, prefix_tree):
```

[Severity: Minor] Complex Method complexity = 19
Found in monitor\core\taps\bgpstreamlive.py:29-159
```
def run_bgpstream(prefixes_file=None, projects=[], start=0, end=0):
```

[Severity: Minor] Complex Method complexity = 18
Found in monitor\core\taps\betabmp.py:27-145
```
def run_bgpstream_beta_bmp(prefixes_file=None):
```

[Severity: Minor] Complex Method complexity = 16
Found in monitor\core\taps\bgpstreamhist.py:21-94
```
def parse_bgpstreamhist_csvs(prefixes_file=None, input_dir=None):
```

**Comment by slowr** [comment]
duplicate from #377
