### ISSUE TITLE
Frequency of BGP glass checks

### ISSUE THREAD

**Issue by mrdavi5** [FORTH-ICS-INSPIRE/artemis#223]
what is the frequency of the checks for the BGP remote looking glasses, can we force a check? can we change this frequency check?

**Comment by vkotronis** [comment]
Closing since question is answered. Feel free to reopen please if more information is required.

**Comment by mrdavi5** [comment]
Hey, Sorry to reopen but now I have it set up in a test environment, within the BGP updates tab is this only populating rows if changes have occurred or should it have a  live stream of each request response from the collectors regardless of changes or not?

**Comment by slowr** [comment]
@mrdavi5 all BGP updates that are received based on your configuration's prefixes will be added in the BGP updates tab with the collector name.
