### ISSUE TITLE
Check database access queries and optimize with extra PG indexes

### ISSUE THREAD

**Issue by vkotronis** [FORTH-ICS-INSPIRE/artemis#228]
**Describe the bug**
When the DB reaches millions of BGP updates in size, the database access queries (at least some of them) seem to introduce large delays. This is hard to replicate, since we typically recommend cleaning up the DB against stale BGP updates and hijack alerts.

**Affected Component(s)**
- [X] Back-End (Database, Microservices, Containers, etc)
- [ ] Front-End (Flask, API, etc)
- [ ] Docs
- [ ] Build System

**To Reproduce**
1. Create a DB with millions of entries (you can create the updates in a hist file and feed it to ARTEMIS)
2. Try out search, reconfiguration and other functions and note down what takes the longest in the DB, query by query.
3. After isolating the query (queries), optimize using additional indexes if required (or modifying the existing ones).

**Expected behavior**
The DB size should have minuscule effect on the delays of user-tool interactions.

**Comment by vkotronis** [comment]
This issue will require careful re-check of the queries and performance testing, moving to next major release 1.4.0. Estimated time for completion: 1-2 work-days.

**Comment by vkotronis** [comment]
@slowr should I move this to next release so that you deal with the https://github.com/FORTH-ICS-INSPIRE/artemis/pull/283 PR in more detail by the 1.4.0 release? It is fine with me, so that we prioritize.

**Comment by vkotronis** [comment]
@slowr is this issue still relevant and can we improve sth else? Or are we in a decent state?

**Comment by slowr** [comment]
it seems to be ok for now. closing the issue
