### ISSUE TITLE
When ARTEMIS restarts, reset the modules to last known state

### ISSUE THREAD

**Issue by vkotronis** [FORTH-ICS-INSPIRE/artemis#231]
**Is your feature request related to a problem? Please describe.**
When ARTEMIS restarts, modules are auto-set to "OFF". It would be more intuitive to set them to the last known state (if "ON", then "ON").

**Describe the solution you'd like**
Store module state in db and query it upon ARTEMIS boot; activate modules that should be activated.

**Comment by alistairking** [comment]
This is especially necessary in a k8s environment where pods can be restarted without notice at any time. Without this feature, a pod restart effectively turns ARTEMIS off.

**Comment by vkotronis** [comment]
Yes. I think we need an additional table in the DB that stores the "intended" state of the modules (currently we correctly store the current supervisor state, but upon restart this is always OFF since the modules shut down during restart).

So we need sth like:
```
CREATE TABLE IF NOT EXISTS intended_module_states (
    name VARCHAR (32) UNIQUE,
    should_be_running BOOLEAN DEFAULT FALSE
);
```

And when the frontend sets sth to on or off, this should also be stored there (independently from the supervisor). When the backend starts, it should read this from the db and instruct the supervisor to set the modules to their intended state. Autorun should remain false in services.conf, since this is independent.

**Comment by vkotronis** [comment]
@alistairking as a temporary solution, and if you know exactly what modules need to always run persistently upon pod restarts, set "autostart=false" to the services.conf of the supervisor daemon for monitor, detection and/or mitigation. We will make the enhancement so that the restart is a bit smarter, but autostart seems to work fine on the local installation I tried (docker-compose, you can check for kubernetes).

**Comment by alistairking** [comment]
Thanks, I'll give that a try now.

**Comment by alistairking** [comment]
Confirmed that this workaround seems to do the trick. Thanks!

**Comment by vkotronis** [comment]
Moving this to the next big release instead of the minor bug-fix release, since the autostart deals with this for now.
