### ISSUE TITLE
Restart detector if detection queue fails due to load

### ISSUE THREAD

**Issue by vkotronis** [FORTH-ICS-INSPIRE/artemis#237]
**Describe the bug**
Currently under severe load circumstances the detection queue might fail with the detector still running, and no error message. We have to make sure detection gracefully restarts after this happens.

**Affected Component(s)**
- [X] Back-End (Database, Microservices, Containers, etc)
- [ ] Front-End (Flask, API, etc)
- [ ] Docs
- [ ] Build System

**To Reproduce**
Severe load on detector.

**Expected behavior**
The detector, even if losing some messages, should gracefully restart and reinstate the queue.

**Comment by vkotronis** [comment]
@slowr maybe we can simply set the maximum number of items in the queue to sth like 10,000 to always fit in an average RAM and never get evicted to disk? Or can we have a try-except statement that properly catches a malfunctioning queue due to extreme load and re-declare? I assume this affects only the queues between db and detection correct?

Are there other alternatives on how to handle this --potential-- issue? Except for replacing RMQ of course :) .

**Comment by vkotronis** [comment]
Moving this to 1.4.0 to focus on testing for the 1.3.1 release.

**Comment by vkotronis** [comment]
Pending here: comment by @slowr on highly available RMQ setup to avoid message loss.
Both for compose and k8s.

**Comment by slowr** [comment]
This behavior stopped appearing after fixing the Postgres bug.. Seemed like it was system load issue related. Will reopen issue if we see this arise again.
