### ISSUE TITLE
Proper migration of hasura queries

### ISSUE THREAD

**Issue by vkotronis** [FORTH-ICS-INSPIRE/artemis#243]
**Is your feature request related to a problem? Please describe.**
When we want to change a query (e.g., change permissions or views), things break on existing databases with pre-existing views of the same name. Check how to properly migrate!

**Additional context**
https://docs.hasura.io/1.0/graphql/manual/migrations/existing-database.html

**Comment by vkotronis** [comment]
For metadata only (which is of interest to us):
https://docs.hasura.io/1.0/graphql/manual/migrations/auto-apply-migrations.html#applying-only-metadata

When this issue is mastered, we can change the current hasura metadata 
(example: user permissions for intended_process_states).

**Comment by vkotronis** [comment]
Check also https://github.com/FORTH-ICS-INSPIRE/artemis/commit/195b83217c4edfe235715ccc6d5b879b89734e81

**Comment by slowr** [comment]
@vkotronis this issue turned out to have no actions as we already provide the schema through the `hasura_init.json` file and the hasura container can be fully ephemeral. Closing it, feel free to re-open if I am missing something.
