### ISSUE TITLE
Testcafe + Graphql query for custom BGP updates

### ISSUE THREAD

**Issue by vkotronis** [FORTH-ICS-INSPIRE/artemis#247]
**Is your feature request related to a problem? Please describe.**
This is useful for frontend testing with TestCafe (live BGP update input to be registered in the DB).

**Describe the solution you'd like**
Button + query to write update on DB via gql.

**Describe alternatives you've considered**

**Additional context**

**Comment by vkotronis** [comment]
Actually button can be optional, we can directly use curl for the query (please document an example).

**Comment by vkotronis** [comment]
TODO:
[ ] @slowr to describe exactly the steps to use graphql and testcafe to create a new test
[ ] @vkotronis to implement the steps and resolve the issue with a new testcafe test PR.

**Comment by slowr** [comment]
So we can query `/graphql` endpoint directly to create hijacks right now by doing a curl command like this:

```
#!/bin/bash
# get access token
access_token=$(curl -k -X POST -H "Content-Type: application/json" -d '{"username":"admin", "password":"admin123"}' https://localhost/jwt/auth | jq -r .access_token)

# write the query inside a json file
cat <<EOF >query.json 
{"query": "mutation insertHijack {
  insert_view_hijacks(objects: {active: true, comment: \"\", community_annotation: \"\", configured_prefix: \"10.0.0.0/8\", dormant: false, hijack_as: \"1\", ignored: false, key: \"1\", num_asns_inf: 10, num_peers_seen: 10, outdated: false, prefix: \"10.0.0.0/8\", resolved: false, seen: false, type: \"S|-|-|-\", under_mitigation: false, withdrawn: false, time_detected: \"2019-11-16T00:00:15.003573\"}) {
    returning {
      key
    }
  }
}"}
EOF

# insert the hijack
curl -k -X POST -H "Content-Type: application/json" -H "Authorization":"Bearer $access_token" https://localhost/api/graphql -d @query.json
```

In order to be able to insert bgp updates as well we need to change the view on the database to include the bgp key and also the hasura metadata.

**Comment by slowr** [comment]
useful information
https://testcafe-discuss.devexpress.com/t/is-it-possible-to-run-shell-commands-from-test/1025

**Comment by vkotronis** [comment]
Closing since tests will be done with cypress and new logic in next.js-based frontend.
