### ISSUE TITLE
Better way to copy/export a single hijack

### ISSUE THREAD

**Issue by pixitha** [FORTH-ICS-INSPIRE/artemis#257]
**Is your feature request related to a problem? Please describe.**
When you try to export a single hijack (for an email or something) it doesn't filter the export of the table and attempts to export the whole thing.

Copying the hijack from the GUI results in a terribly formatted copy

**Describe the solution you'd like**
The table export button should filter to that exact hijack using the event ID.

The view table could have a copy button that only has the data from the gui, but in a simple format designed to be copied.

**Describe alternatives you've considered**
n/a

**Additional context**
slowr has a copy of a private screenshot of an event.

**Comment by vkotronis** [comment]
@pgigis you can add a "Download" button also on the hijack export page (currently you can download the BGP update table from there, but we need also the rest of the hijack information, preferably in exportable json format; this can also include the BGP updates or not, up to you (we can treat the BGP updates and the hijack updates as 2 separate queries or a single one - for downloading/exporting data; feel free to choose any of the two approaches you deem best.

**Comment by vkotronis** [comment]
Related to https://github.com/FORTH-ICS-INSPIRE/artemis/issues/446 . Both these issues will be addressed after the major frontend refactoring we are undergoing finishes (after the next milestone).
