### ISSUE TITLE
Ability to select all on hijacks page (based on filtered view)

### ISSUE THREAD

**Issue by pixitha** [FORTH-ICS-INSPIRE/artemis#261]
**Is your feature request related to a problem? Please describe.**
Very tedious to delete or ignore, resolve etc. on the hijacks page as you have to slowly/manually click each prefix to select it.

**Describe the solution you'd like**
A button on the page to automatically select all of the visible prefixes on the screen. After the filter is applied.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by vkotronis** [comment]
@pgigis could you take a look at this on the frontend side? You can add a small rectangular checkmark near the number of entries indicator to be able to select/deselect all entries. Should be relatively straightforward to implement.
