### ISSUE TITLE
Replace multiple SELECT queries using execute_batch with execute

### ISSUE THREAD

**Issue by pgigis** [FORTH-ICS-INSPIRE/artemis#262]
**Describe the bug**

In file database.py at function handle_hijack_update() we use psycopg2.extras.execute_batch to perform a mulitple selects.  

According to https://github.com/psycopg/psycopg2/issues/720 this is not supported and only the element from the last SELECT query is being returned.

**Affected Component(s)**
- [X] Back-End (Database, Microservices, Containers, etc)
- [ ] Front-End (Flask, API, etc)
- [ ] Docs
- [ ] Build System

**To Reproduce**

**Expected behavior**

**Screenshots**

**System (please complete the following information):**

**Additional context**

**Comment by vkotronis** [comment]
Affected query (only one):
https://github.com/FORTH-ICS-INSPIRE/artemis/blob/master/backend/core/database.py#L592

Please issue a quick-fix PR
