### ISSUE TITLE
Optimize code/script reuse for detection and autoconf testers

### ISSUE THREAD

**Issue by vkotronis** [FORTH-ICS-INSPIRE/artemis#267]
```
docker build -t artemis_tester -f tester/Dockerfile ./tester/detection/
```
coveragerc is not even needed in these containers btw it's run from the outside
```
docker run -v ${PWD}/tester/wait-for:/root/wait-for artemis_tester
```

**Comment by slowr** [comment]
After thinking about this issue I believe that it is better to have the code duplicated as it gives us more flexibility to have changes per deployment. It might make the maintenance a bit more difficult but if we have it in mind it should not be a problem.

What do you think @vkotronis ?

**Comment by vkotronis** [comment]
Closing since this is not an actionable issue anymore.
