### ISSUE TITLE
Unintended process_states exposure!?

### ISSUE THREAD

**Issue by marcgweg** [FORTH-ICS-INSPIRE/artemis#290]
**Describe the bug**
There is an undocumented URL found during pentest of Artemis. The URL is https://artemis/proxy_api?download_table=true&action=process_states

**Affected Component(s)**
- [ ] Back-End (Database, Microservices, Containers, etc)
- [X] Front-End (Flask, API, etc)
- [ ] Docs
- [ ] Build System

**To Reproduce**
1. Go to 'https://artemis/proxy_api?download_table=true&action=process_states'
2. See JSON output.

**Expected behavior**
Euh, nothing I guess? Seems like an internal "are you alive" JSON output for monitoring!?

**JSON output in browser**
[
  {
    "name": "mitigation",
    "running": false,
    "timestamp": "2019-12-16T08:39:10.849954"
  },
  {
    "name": "clock",
    "running": true,
    "timestamp": "2019-12-16T08:39:12.067733"
  },
  {
    "name": "configuration",
    "running": true,
    "timestamp": "2019-12-16T08:39:12.084261"
  },
  {
    "name": "database",
    "running": true,
    "timestamp": "2019-12-16T08:39:12.086263"
  },
  {
    "name": "observer",
    "running": true,
    "timestamp": "2019-12-16T08:39:12.088817"
  },
  {
    "name": "monitor",
    "running": true,
    "timestamp": "2019-12-16T08:39:14.067809"
  },
  {
    "name": "detection",
    "running": true,
    "timestamp": "2019-12-16T08:39:17.017864"
  }
]

**System (please complete the following information):**
 - OS: [e.g. iOS] CentOS7
 - Browser [e.g. chrome, safari] N/A
 - Version [e.g. 22] 20

**Additional context**

**Comment by vkotronis** [comment]
To the best of my knowledge, this is simply a graphql query exposed over the proxy API so that the web application can retrieve the information on the different processes that are running (or not running) in the system. So the exposure is intended. However, I will double-check with @slowr and @pgigis to be sure about the intention of this.

**Comment by marcgweg** [comment]
One of my red team members has issued some pentests against Artemis, nothing shocking (but this) came out of it. So we're tearing down the test bed, and initiate the Epic to build up Artemis in a High Availability cluster for production. 👍

**Comment by slowr** [comment]
@marcgweg thanks a lot for pointing this vulnerability out. You are not supposed to be able to access this endpoint while not being authenticated. I will issue a fix asap :)

**Comment by slowr** [comment]
@marcgweg the patch is merged on master. We will release a minor artemis version these days that will include the fix. By the way, if you have readable reports from the penetration test we would love to have them on a wiki page on the repository. Thanks again!
