### ISSUE TITLE
Explicit user-controlled deletion of multiple hijacks

### ISSUE THREAD

**Issue by vkotronis** [FORTH-ICS-INSPIRE/artemis#32]
**Is your feature request related to a problem? Please describe.**
The user currently cannot delete hijacks using the UI

**Describe the solution you'd like**
This should be done after https://github.com/FORTH-ICS-INSPIRE/artemis/issues/34 is solved (will require hasura for "IN"-like searching in key lists).

UI button and backend db functionality to delete multiple hijacks and their related BGP updates.
Make sure that there is an "Are you sure?" banner before confirming final deletion.
This issue needs frontend support (UI) via graphql (delete hijacks and updates from db).
Delete only updates that belong to a single hijack, remove the key from the ones that belong to multiple (like withdrawals). Make sure that the UI is usable during the transition (e.g., you can delete first the hijack events and then the updates for safety).
We need a "delete" button within a hijack, and "delete" in the hijack table for multiple hijacks.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by pgigis** [comment]
Use graphql API.

**Comment by pgigis** [comment]
We should delete only non-active hijacks.

**Comment by pgigis** [comment]
Use rabbitmq
