### ISSUE TITLE
frontend: stats.ripe.net/geoloc/data.json?resource=AS1200 ERROR

### ISSUE THREAD

**Issue by maq123** [FORTH-ICS-INSPIRE/artemis#342]
**Describe the bug**

Artemis performs the following query when hovering over the hijack's AS number:

https://stat.ripe.net/data/geoloc/data.json?resource=AS1200 (example AS 1200 here).

This gives:

```

  |  
-- | --
status | "error"
server_id | "app009"
status_code | 400
version | "1.0"
cached | false
see_also | []
time | "2020-03-02T15:39:26.683994"
messages |  
0 |  
0 | "error"
1 | "AS1200 is of unsupported type ASN. It should be an IP prefix."
data_call_status | "supported"
process_time | 0
build_version | "2020.3.2.192"
query_id | "20200302153926-5f6a0298-302c-420e-ad6e-9dc049bba5cf"
data | {}


```

It seems IP prefix needs to be given as the parameter no ASN.

**Affected Component(s)**
- [ ] Back-End (Database, Microservices, Containers, etc)
- [x] Front-End (Flask, API, etc)
- [ ] Docs
- [ ] Build System

**To Reproduce**
1. Go to 'hijacks'
2. Click on 'however over the as number of a hijack'
3. Fire up the the developer tools of your browser and look at the return codes of queries performed to stats.ripe.net

**Expected behavior**
AS info should be fetched and presented when howering over ASN.

**Comment by slowr** [comment]
Thanks for pointing this out @pgigis is already working to fix this.

**Comment by pgigis** [comment]
Hi, 

thanks for reporting the issue. It seems that RIPE Stat modified their API.
I pushed a fix https://github.com/FORTH-ICS-INSPIRE/artemis/commit/548fbe5d232bd41bed4a21d8382adf7bd33abf5b which resolves the issue.

If you are using the docker containers please pull the new images.

Petros

**Comment by pgigis** [comment]
There was an issue with the building of the docker containers.
The problem should be now fixed.

I am closing this issue.

**Comment by maq123** [comment]
Hi Guys,

thx for fixing.
it seems that RIPE has fix the API and the call I reported works again.
I just noticed it while planning to upgrade my artmis instance that things work again...

```
https://stat.ripe.net/data/geoloc/data.json?resource=AS1200


  |  
-- | --
status | "ok"
server_id | "app026"
status_code | 200
version | "1.0"
cached | false
see_also | []
time | "2020-03-12T10:06:13.694019"
messages | []
data_call_status | "supported"
process_time | 441
build_version | "2020.3.11.195"
query_id | "20200312100613-64d806eb-c745-4cd3-9324-d6a7992714ea"
data |  
located_resources |  
0 |  
resource | "1200"
location | "NL"
result_time | "2020-03-11T00:00:00"
latest_time | "2020-03-11T00:00:00"
earliest_time | "2005-02-18T00:00:00"
parameters |  
query_time | "2020-03-11T00:00:00"
resource | "1200"
```
