### ISSUE TITLE
Monitoring Hijacking with only internal interface

### ISSUE THREAD

**Issue by Tyrell20** [FORTH-ICS-INSPIRE/artemis#361]
Hello,
I do not understand clearly if to monitor eventually hijacking attack is needed the public interface or I can use only internal network interface.

Many thanks for your support

**Comment by slowr** [comment]
Hi @Tyrell20 ,

The tool support both public and private sources for monitors.

By default we use BGPStream and Ripe RIS public feeds which means that you need to give it internet connection so it is able to connect to the services.

On the other hand, you can connect your own BGP router as an ARTEMIS monitor by following this [guide](https://github.com/FORTH-ICS-INSPIRE/artemis/wiki#receiving-bgp-feed-from-local-routerroute-reflectorbgp-monitor-via-exabgp). The only problem with the second approach is that the visibility is limited to what your BGP router is seeing.

Best,
Dimitris

**Comment by slowr** [comment]
I am closing this issue, if you have any additional questions feel free to ask here again
