### ISSUE TITLE
Make sure that coverage is over 90% in codecov by refactoring

### ISSUE THREAD

**Issue by vkotronis** [FORTH-ICS-INSPIRE/artemis#378]
**Describe the bug**
Current coverage is at 87%.

**Affected Component(s)**
- [X] Back-End (Database, Microservices, Containers, etc)
- [X] Front-End (Flask, API, etc)
- [ ] Docs
- [ ] Build System

**Additional context**
https://codecov.io/gh/FORTH-ICS-INSPIRE/artemis

**Comment by slowr** [comment]
Coverage hit 90%, this can stop being an issue and try to keep it as high in the future.
