### ISSUE TITLE
Watch if db clock is missing seconds

### ISSUE THREAD

**Issue by slowr** [FORTH-ICS-INSPIRE/artemis#379]
**Is your feature request related to a problem? Please describe.**
We have a db-clock queue that receives an event every one second in the database module in order to trigger the bgp updates handler. 

If we have queries that take too much time, the queue gets bigger and bigger, meaning that it is loosing seconds of processing.

**Describe the solution you'd like**
We need to have a way to check if this clock is getting bigger and bigger and have a threshold that notifies the user that there is  problem. For example, if the db-clock is above 60 and increasing this means that there is a running query of 1 minute+.

We can also report the query that takes this time so it is easier for us to debug afterwards and find database bottlenecks.

**Comment by vkotronis** [comment]
Correct, and also please check what happens with the accumulated messages in the queue. E.g., if we have 10 clock signals in the queue the DB actually needs to implement only one to reinstate timing, and ignore the rest (we may have to change the logic for the scheduler, let's discuss when you start on the issue).

**Comment by vkotronis** [comment]
This will be addressed by the decoupled arch of https://github.com/FORTH-ICS-INSPIRE/artemis/pull/472 (when that works and is merged, we can also close this issue).

**Comment by vkotronis** [comment]
Update: this issue can be definitely closed after #472 is merged. We are using threaded timers there; monitoring the performance of the DB calls can be an orthogonal issue (there is not explicit clock signal any more).

**Comment by vkotronis** [comment]
Closed by #472
