### ISSUE TITLE
Hijack view needs additional tooltips

### ISSUE THREAD

**Issue by vkotronis** [FORTH-ICS-INSPIRE/artemis#38]
**Is your feature request related to a problem? Please describe.**
On hijack view, the tooltip for the hijacker AS on the hijack table and for the route collectors on the bgp update table are not activated.

**Describe the solution you'd like**
Add/activate the tooltips, as done in other tables (e.g., BGP update).
Also check that the route collector tooltip works in "More" view within a BGP update entry of the hijack view.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by vkotronis** [comment]
@pgigis Is this fixed? If yes, with what PR?

**Comment by pgigis** [comment]
Resolved by https://github.com/FORTH-ICS-INSPIRE/artemis/pull/45
