### ISSUE TITLE
Security settings could be better

### ISSUE THREAD

**Issue by marcgweg** [FORTH-ICS-INSPIRE/artemis#381]
Hi all,

Could you please look into the following report as generated by a Nikto scan on a running Artemis server?

- Nikto v2.1.6
---------------------------------------------------------------------------
+ Target IP:          <>
+ Target Hostname:    <>
+ Target Port:        80
+ Start Time:         2020-05-13 03:25:14 (GMT-4)
---------------------------------------------------------------------------
+ Server: nginx/1.17.10
+ The anti-clickjacking **X-Frame-Options** header is not present.
+ The **X-XSS-Protection** header is not defined. This header can hint to the user agent to protect against some forms of XSS
+ The **X-Content-Type-Options** header is not set. This could allow the user agent to render the content of the site in a different fashion to the MIME type
+ Root page / redirects to: https://<>/

+ 26522 requests: 0 error(s) and 3 item(s) reported on remote host
+ End Time:           2020-05-13 03:43:19 (GMT-4) (1085 seconds)
---------------------------------------------------------------------------
+ 1 host(s) tested

- Nikto v2.1.6
---------------------------------------------------------------------------

+ Target IP:          <>
+ Target Hostname:    <>
+ Target Port:        443
---------------------------------------------------------------------------
+ SSL Info:        Subject:  /C=GR/ST=Crete/L=Heraklion/O=FORTH/OU=ICS-FORTH/CN=ARTEMIS TEST/emailAddress=gkigkis@ics.forth.gr
                   Ciphers:  ECDHE-RSA-AES256-GCM-SHA384
                   Issuer:   /C=GR/ST=Crete/L=Heraklion/O=FORTH/OU=ICS-FORTH/CN=ARTEMIS TEST/emailAddress=gkigkis@ics.forth.gr
+ Start Time:         2020-05-13 03:25:15 (GMT-4)
---------------------------------------------------------------------------
+ Server: nginx/1.17.10

+ The anti-clickjacking **X-Frame-Options** header is not present.
+ The **X-XSS-Protection** header is not defined. This header can hint to the user agent to protect against some forms of XSS
+ The site uses SSL and the **Strict-Transport-Security HTTP** header is not defined.
+ The site uses SSL and **Expect-CT** header is not present.
+ The **X-Content-Type-Options** header is not set. This could allow the user agent to render the content of the site in a different fashion to the MIME type
+ Root page / redirects to: http://<>/login

+ Hostname '<>' does not match certificate's names: ARTEMIS

+ **Server may leak inodes via ETags**, header found with file /favicon.ico, inode: 1588929021.0, size: 562, mtime: 2293567721

+ Allowed HTTP Methods: OPTIONS, HEAD, GET, POST 

+ Web Server returns a valid response with junk HTTP methods, this may cause false positives.

+ Scan terminated:  19 error(s) and 9 item(s) reported on remote host
+ End Time:           2020-05-13 03:57:20 (GMT-4) (1925 seconds)
---------------------------------------------------------------------------
+ 1 host(s) tested

Best regards,
Marc

**Comment by vkotronis** [comment]
Many thanks for pointing this out Marc! I will check with @slowr and @pgigis to address any security vulnerabilities may exist in the frontend application. In the meanwhile, PRs to patch some of them (if you know exactly what needs to be fixed per sub-issue), are most welcome!

**Comment by slowr** [comment]
Thanks a lot for the penetration testing; you gave me the idea to add it on the pipeline for the releases as well. 

I am going to look into the header issues that you reported (some of them are false positives like the certificate which is supposed to only work for local setups)

**Comment by slowr** [comment]
We fixed all the warnings that were because of our stack but have in mind that most of the issues are the setup of the nginx server and ssl certificates which should be done by your side! 
Thanks again for reporting the issue!

**Comment by marcgweg** [comment]
HI,

Thanks, and yes I know the SSL certificates were still your test ones, I am in the midst of replacing them by the correct production ones.
And I’ll check the Nginx setup on these issues.

Best regards,
Marc
