### ISSUE TITLE
Allow user creation from user management GUI

### ISSUE THREAD

**Issue by kruisdraad** [FORTH-ICS-INSPIRE/artemis#392]
Generally its a bad idea to enable user registration for anyone, so i rather disable that. However if i do, there is no alternative to make users from an administrator perspective.

Please allow a 'create user' option from the user management.

**Comment by vkotronis** [comment]
@pgigis could you take a look at this? Essentially we need a simple form for an admin to create a new user (and check if we disable the registration feature and instead redirect the user to a force-password-change form when the user connects for the first time). So workflow:
1) admin creates new user and sets a new password
2) user connect with the password and is redirected to a force passwd change form
3) user updates the password (which is from now on known only to him)
We probably do not need the user reg form with this.

@slowr do you also agree with this approach? We also support LDAP and radius currently, so this admin-based perspective will complement nicely the existing mechanisms.

**Comment by slowr** [comment]
> @pgigis could you take a look at this? Essentially we need a simple form for an admin to create a new user (and check if we disable the registration feature and instead redirect the user to a force-password-change form when the user connects for the first time). So workflow:
> 
> 1. admin creates new user and sets a new password
> 2. user connect with the password and is redirected to a force passwd change form
> 3. user updates the password (which is from now on known only to him)
>    We probably do not need the user reg form with this.
> 
> @slowr do you also agree with this approach? We also support LDAP and radius currently, so this admin-based perspective will complement nicely the existing mechanisms.

Sounds like the best approach to me. 👍

**Comment by vkotronis** [comment]
Since we are heavily refactoring the frontend with react.js, this issue will be moved in another milestone after 1.6.0.

**Comment by vkotronis** [comment]
Addressed in new frontend (to be released): https://github.com/FORTH-ICS-INSPIRE/artemis-web
