### ISSUE TITLE
Session expired, GUI doesnt know

### ISSUE THREAD

**Issue by kruisdraad** [FORTH-ICS-INSPIRE/artemis#395]
Log in, go to system configuration then wait until session expires.

Using the webgui, goint to edit the current configuration. Click edit, then remove the entire current config and paste a new configuration. The new configuration consists of 1431 (a lot of) lines then click save. The engine will be stuck in 'pending' forever.

Expect: when trying action and session is no longer valid redirect to login page instead of trying to submit new config.

**Comment by slowr** [comment]
Hey, thanks for the report.

I am going to take a look into it, it's an external API call so I will need to see if the redirect is possible
