### ISSUE TITLE
Changing HASURA_SECRET_KEY results in 403 error

### ISSUE THREAD

**Issue by kruisdraad** [FORTH-ICS-INSPIRE/artemis#398]
When you changes the HASURA_SECRET_KEY in the .env from '@rt3m1s.' into a strong password, the systems reports 403 errors:

```
messaging - 2020-06-03 11:25:18,426 - INFO @ _receive_callback: Monitor initiated, configured and running.
messaging - 2020-06-03 11:25:18,463 - ERROR @ _receive_callback: exception
Traceback (most recent call last):
  File "core/utils/__init__.py", line 380, in core.utils.__init__.signal_loading
  File "/usr/local/lib/python3.7/dist-packages/gql/client.py", line 76, in execute
    raise Exception(str(result.errors[0]))
Exception: {'extensions': {'path': '$', 'code': 'access-denied'}, 'message': 'invalid x-hasura-admin-secret/x-hasura-access-key'}
```

Setting it back to default results in no more errors as far as i can tell. 

Looking at the https://hasura.io/docs/1.0/graphql/manual/deployment/graphql-engine-flags/reference.html i do not see this variable, might this been changed into another variable?

**Comment by slowr** [comment]
Seems that hasura changed the environment variable name when releasing the 1.0 version to `ADMIN_SECRET_KEY`. Will change the variable in .env and add backwards compatibility.

**Comment by slowr** [comment]
@kruisdraad for me it works correctly with the deprecated flag (we will add the new one as well but is not your actual issue).

I guess in your case you initialized the hasura container with the old password, stopped the container, changed the password and started again.

In that case the old password remains as the admin password as you never actually destroyed the container. To restart the deployment from clean state (no worries database/config remains) you need to run `docker-compose down -v`.

Feel free to re-open the ticket if the problem persists.

**Comment by kruisdraad** [comment]
@slowr i have regenerated the containers before sending, so i stopped it and docker RM (all containers btw) then started them again. I have done this several times to make sure i have a clean env while debugging the BMP issues. Maybe its no longer depricated ( i am running latest)?

I am going to debug this after i got the BMP fixed, one thing at the time :)
