### ISSUE TITLE
BSD support

### ISSUE THREAD

**Issue by cardosocristian** [FORTH-ICS-INSPIRE/artemis#422]
It would be possible to provide an installation manual for this tool, for environments where there is no docker running, like in BSD environments

**Comment by slowr** [comment]
Hi @cardosocristian, thanks for reaching out.

Currently there are no plans for supporting a non docker environment as we can't do the orchestration that we want.

If you want you can try adding support for BSD and becoming a contributor. I will keep this in the backlog but it's not a priority for now.

**Comment by cardosocristian** [comment]
Unfortunately I don't know how to program, I'm sorry.
