### ISSUE TITLE
Remove timescale, move to native postgres

### ISSUE THREAD

**Issue by pgigis** [FORTH-ICS-INSPIRE/artemis#43]
**Is your feature request related to a problem? Please describe.**
Nope

**Describe the solution you'd like**
Create migration for the container and the previous db.

**Describe alternatives you've considered**
NA

**Additional context**
Check this:
https://docs.timescale.com/v1.1/using-timescaledb/update-db

**Comment by vkotronis** [comment]
@pgigis let's keep this issue dormant for now since it requires a complex workflow on the deployer's side. We can select of we upgrade formally with a breaking change in ARTEMIS-2.0.0.

**Comment by pgigis** [comment]
We should remove timescale, move to native postgres 11

**Comment by slowr** [comment]
Doing some performance measurements it seems that postgres and timescale are on-par to the same performance while timescale provides some more functionality. For that reason I will close this ticket until we decide that a database migration is really needed.
