### ISSUE TITLE
Width of hijacks window not scaling/scrolling

### ISSUE THREAD

**Issue by pixitha** [FORTH-ICS-INSPIRE/artemis#430]
**Describe the bug**
When the content in the ongoing hijack box on the main screen is wider than the window size the box cuts off the right hand fields. No scroll bars or scrolling are working either. I have to shrink (zoom out) the window to 75% to get it all to fit.

**Affected Component(s)**
- [ ] Back-End (Database, Microservices, Containers, etc)
- [x] Front-End (Flask, API, etc)
- [ ] Docs
- [ ] Build System

**To Reproduce**
Have any alert hijack for IPv6 will probably be long enough to make it happen.

**Expected behavior**
Either the fields should allow scrolling left and right, or autoshrink to fit the content

**Screenshots**
<img width="991" alt="Screen Shot 2020-09-09 at 11 40 04 AM" src="https://user-images.githubusercontent.com/503771/92621417-ca833e80-f291-11ea-983a-f2d6dd35eb66.png">
<img width="990" alt="Screen Shot 2020-09-09 at 11 41 14 AM" src="https://user-images.githubusercontent.com/503771/92621425-ce16c580-f291-11ea-9985-3d59b134f217.png">

**System (please complete the following information):**
 - OS: MacOS 10.15.6
 - Browser: Chrome 
 - Version: 85.0.4183.83

**Comment by slowr** [comment]
Thanks a lot for reporting the issue!
We are currently undergoing a frontend botox so we will make sure this issue is fixed. I will keep this ticket open until we have results :)

**Comment by vkotronis** [comment]
Addressed in new frontend (to be released): https://github.com/FORTH-ICS-INSPIRE/artemis-web
