### ISSUE TITLE
Enable hijack exporting in PDF (or similar format)

### ISSUE THREAD

**Issue by stkonst** [FORTH-ICS-INSPIRE/artemis#446]
It would be nice to export the details of a specific hijack in a PDF (or similar standardized) format, for documentation reasons or sharing with colleagues from other organizations. 

What we do now is to take print-screens of the hijack and store 1-2 png files, which is not ideal. 

Thank's guys and I remain available for further questions.

**Comment by slowr** [comment]
We are currently ongoing a frontend refactoring/restructure that will support this feature. Will add it to the backlog as a reference!

Thanks for the feature request

**Comment by vkotronis** [comment]
Closed by #565
