### ISSUE TITLE
Substitute wiki links with docs links in /docs

### ISSUE THREAD

**Issue by vkotronis** [FORTH-ICS-INSPIRE/artemis#454]
**Is your feature request related to a problem? Please describe.**
Currently many of the links we have in the docs still point to old wiki pages (they need to point to the new docs).

**Describe the solution you'd like**
Substitute the old links with new ones.

**Additional context**
Example: https://bgpartemis.readthedocs.io/en/latest/gettingstarted/#minimum-technical-requirements
(and many more), where links point to the wiki instead of the new docs sections.

**Comment by vkotronis** [comment]
First, search for the work `wiki` within the artemis repo, filtering for `*.md` files. Check and substitute correctly.

**Comment by chawlapalak** [comment]
Hi there,
I can try to work on this one starting today. Please assign it to me.
Thanks.

**Comment by vkotronis** [comment]
Thank you @chawlapalak ! Feel free to issue a Pull Request (PR) when ready. Essentially we want to take out wiki links from docs and use only either in-repo code links or in-docs links (in https://bgpartemis.readthedocs.io/en/). Cheers!

**Comment by vkotronis** [comment]
@chawlapalak have you checked this issue? Thanks in advance!

Please also make sure that you check [this guide](https://github.com/FORTH-ICS-INSPIRE/artemis/blob/master/CONTRIBUTING.md)

**Comment by vkotronis** [comment]
I am working on this issue in parallel.

**Comment by vkotronis** [comment]
Closed via https://github.com/FORTH-ICS-INSPIRE/artemis/commit/983b7523b8fcffb3ec7d01c559845c9744b9ef11
