### ISSUE TITLE
Discard BGP updates on real-time feeds with very old timestamps

### ISSUE THREAD

**Issue by vkotronis** [FORTH-ICS-INSPIRE/artemis#473]
**Describe the bug**
It may happen that BGP updates with timestamps older than 1 hour in the past get in real-time feeds. If ARTEMIS restarts during that time, it may happen that they are replayed (e.g., by BGPStream) and then cause collisions on the database.

**Affected Component(s)**
- [X] Back-End (Database, Microservices, Containers, etc) --> Monitors
- [ ] Front-End (Flask, API, etc)
- [ ] Docs
- [ ] Build System

**Expected behavior**
Old timestamped updates should be discarded.

**Comment by vkotronis** [comment]
@slowr we already have safe-guards for this though:
https://github.com/FORTH-ICS-INSPIRE/artemis/blob/master/backend/core/database.py#L869
https://github.com/FORTH-ICS-INSPIRE/artemis/blob/master/utils/artemis_utils/__init__.py#L748
So old updates should not make it in. Maybe it has to do with the UTC vs local timestamps?

**Comment by pixitha** [comment]
`backend           | db_util - 2020-11-03 17:44:23,242 - ERROR @ execute_values: got error duplicate key value violates unique constraint "1_1_bgp_updates_pkey"
backend           | DETAIL:  Key ("timestamp", key)=(2020-11-03 14:49:25, 8f8e5095d61e158a16148cf8f177212b) already exists.. retrying 5
backend           | db_util - 2020-11-03 17:44:24,244 - INFO @ close: PostgreSQL connection is closed
postgres          | 2020-11-03 17:44:24.258 UTC [8512] ERROR:  duplicate key value violates unique constraint "1_1_bgp_updates_pkey"
postgres          | 2020-11-03 17:44:24.258 UTC [8512] DETAIL:  Key ("timestamp", key)=(2020-11-03 14:49:25, 8f8e5095d61e158a16148cf8f177212b) already exists.
postgres          | 2020-11-03 17:44:24.258 UTC [8512] STATEMENT:  INSERT INTO bgp_updates (prefix, key, origin_as, peer_asn, as_path, service, type, communities, timestamp, hijack_key, handled, matched_prefix, orig_path) VALUES ('XXXX:XXXX:7013::/48','8f8e5095d61e158a16148cf8f177212b',XXXXX,XXXXX,ARRAY[XXXXX,6939,XXXXX,XXXXX],'bgpstreamlive|ris|rrc21','A','[[51706,65023],[51706,65011],[51706,64650],[51706,64602]]','2020-11-03T14:49:25'::timestamp,'{}',false,('XXXX:XXXX:7013::/48'),'null')
backend           | messaging - 2020-11-03 17:44:24,259 - ERROR @ _receive_callback: exception
backend           | Traceback (most recent call last):
backend           |   File "/usr/local/lib/pyenv/versions/3.6.8/lib/python3.6/site-packages/artemis_utils/db_util.py", line 145, in execute_values
backend           |     self._cursor, query, vals, page_size=page_size
backend           |   File "/usr/local/lib/pyenv/versions/3.6.8/lib/python3.6/site-packages/psycopg2/extras.py", line 1281, in execute_values
backend           |     cur.execute(b''.join(parts))
backend           | psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "1_1_bgp_updates_pkey"
backend           | DETAIL:  Key ("timestamp", key)=(2020-11-03 14:49:25, 8f8e5095d61e158a16148cf8f177212b) already exists.
backend           | During handling of the above exception, another exception occurred:
backend           | Traceback (most recent call last):
backend           |   File "/usr/local/lib/pyenv/versions/3.6.8/lib/python3.6/site-packages/artemis_utils/db_util.py", line 145, in execute_values
backend           |     self._cursor, query, vals, page_size=page_size
backend           |   File "/usr/local/lib/pyenv/versions/3.6.8/lib/python3.6/site-packages/psycopg2/extras.py", line 1281, in execute_values
backend           |     cur.execute(b''.join(parts))
backend           | psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "1_1_bgp_updates_pkey"
backend           | DETAIL:  Key ("timestamp", key)=(2020-11-03 14:49:25, 8f8e5095d61e158a16148cf8f177212b) already exists.
backend           | During handling of the above exception, another exception occurred:
backend           | Traceback (most recent call last):
backend           |   File "/usr/local/lib/pyenv/versions/3.6.8/lib/python3.6/site-packages/artemis_utils/db_util.py", line 145, in execute_values
backend           |     self._cursor, query, vals, page_size=page_size
backend           |   File "/usr/local/lib/pyenv/versions/3.6.8/lib/python3.6/site-packages/psycopg2/extras.py", line 1281, in execute_values
backend           |     cur.execute(b''.join(parts))
backend           | psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "1_1_bgp_updates_pkey"
backend           | DETAIL:  Key ("timestamp", key)=(2020-11-03 14:49:25, 8f8e5095d61e158a16148cf8f177212b) already exists.
backend           | During handling of the above exception, another exception occurred:
backend           | Traceback (most recent call last):
postgres          | 2020-11-03 17:44:24.261 UTC [8512] ERROR:  current transaction is aborted, commands ignored until end of transaction block
backend           |   File "/usr/local/lib/pyenv/versions/3.6.8/lib/python3.6/site-packages/artemis_utils/db_util.py", line 145, in execute_values
backend           |     self._cursor, query, vals, page_size=page_size
backend           |   File "/usr/local/lib/pyenv/versions/3.6.8/lib/python3.6/site-packages/psycopg2/extras.py", line 1281, in execute_values
backend           |     cur.execute(b''.join(parts))
backend           | psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "1_1_bgp_updates_pkey"
backend           | DETAIL:  Key ("timestamp", key)=(2020-11-03 14:49:25, 8f8e5095d61e158a16148cf8f177212b) already exists.
backend           | During handling of the above exception, another exception occurred:
backend           | Traceback (most recent call last):
backend           |   File "/usr/local/lib/pyenv/versions/3.6.8/lib/python3.6/site-packages/artemis_utils/db_util.py", line 145, in execute_values
backend           |     self._cursor, query, vals, page_size=page_size
backend           |   File "/usr/local/lib/pyenv/versions/3.6.8/lib/python3.6/site-packages/psycopg2/extras.py", line 1281, in execute_values
backend           |     cur.execute(b''.join(parts))
backend           | psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "1_1_bgp_updates_pkey"
backend           | DETAIL:  Key ("timestamp", key)=(2020-11-03 14:49:25, 8f8e5095d61e158a16148cf8f177212b) already exists.
backend           | During handling of the above exception, another exception occurred:
backend           | Traceback (most recent call last):
backend           |   File "core/database.py", line 1247, in core.database.Worker._insert_bgp_updates
backend           |   File "/usr/local/lib/pyenv/versions/3.6.8/lib/python3.6/site-packages/artemis_utils/db_util.py", line 157, in execute_values
backend           |     self.execute_values(query, vals, page_size, retry_counter)
backend           |   File "/usr/local/lib/pyenv/versions/3.6.8/lib/python3.6/site-packages/artemis_utils/db_util.py", line 157, in execute_values
backend           |     self.execute_values(query, vals, page_size, retry_counter)
backend           |   File "/usr/local/lib/pyenv/versions/3.6.8/lib/python3.6/site-packages/artemis_utils/db_util.py", line 157, in execute_values
backend           |     self.execute_values(query, vals, page_size, retry_counter)
backend           |   [Previous line repeated 2 more times]
backend           |   File "/usr/local/lib/pyenv/versions/3.6.8/lib/python3.6/site-packages/artemis_utils/db_util.py", line 150, in execute_values
backend           |     raise error
backend           |   File "/usr/local/lib/pyenv/versions/3.6.8/lib/python3.6/site-packages/artemis_utils/db_util.py", line 145, in execute_values
backend           |     self._cursor, query, vals, page_size=page_size
backend           |   File "/usr/local/lib/pyenv/versions/3.6.8/lib/python3.6/site-packages/psycopg2/extras.py", line 1281, in execute_values
backend           |     cur.execute(b''.join(parts))
backend           | psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "1_1_bgp_updates_pkey"
backend           | DETAIL:  Key ("timestamp", key)=(2020-11-03 14:49:25, 8f8e5095d61e158a16148cf8f177212b) already exists.
backend           | db_util - 2020-11-03 17:44:24,262 - ERROR @ execute_values: got error current transaction is aborted, commands ignored until end of transaction block. retrying 1
postgres          | 2020-11-03 17:44:24.261 UTC [8512] STATEMENT:  UPDATE hijacks SET peers_withdrawn=array_remove(peers_withdrawn, removed.peer_asn) FROM (SELECT witann.key, witann.peer_asn FROM (SELECT hij.key, wit.peer_asn, wit.timestamp AS wit_time, ann.timestamp AS ann_time FROM ((VALUES ('4bd08f982f4d9acadceb728da3f3786d','2d0bcb47c9a0e26bef2b301f3edb794e','2020-10-27T17:44:24.261294'::timestamp)) AS data (v1, v2, v3) LEFT JOIN hijacks AS hij ON (data.v1=hij.key) LEFT JOIN bgp_updates AS ann ON (data.v2=ann.key) LEFT JOIN bgp_updates AS wit ON (hij.key=ANY(wit.hijack_key))) WHERE ann.timestamp >= data.v3 AND wit.timestamp >= data.v3 AND ann.type='A' AND wit.prefix=ann.prefix AND wit.peer_asn=ann.peer_asn AND wit.type='W' ORDER BY wit_time DESC, hij.key LIMIT 1) AS witann WHERE witann.wit_time < witann.ann_time) AS removed WHERE hijacks.key=removed.key
backend           | db_util - 2020-11-03 17:44:25,263 - INFO @ close: PostgreSQL connection is closed
postgres          | 2020-11-03 17:44:26.046 UTC [8513] ERROR:  duplicate key value violates unique constraint "1_1_bgp_updates_pkey"
postgres          | 2020-11-03 17:44:26.046 UTC [8513] DETAIL:  Key ("timestamp", key)=(2020-11-03 14:49:25, 10227d59d3f1382f68b5b236669cdaa0) already exists.
backend           | db_util - 2020-11-03 17:44:26,046 - ERROR @ execute_values: got error duplicate key value violates unique constraint "1_1_bgp_updates_pkey"
postgres          | 2020-11-03 17:44:26.046 UTC [8513] STATEMENT:  INSERT INTO bgp_updates (prefix, key, origin_as, peer_asn, as_path, service, type, communities, timestamp, hijack_key, handled, matched_prefix, orig_path) VALUES ('xxx:xxxx:xxxx::/48','10227d59d3f1382f68b5b236669cdaa0',XXXXX,XXXXX,ARRAY[XXXXX,XXXXX,XXXXX,XXXXX],'bgpstreamlive|ris|rrc21','A','[[XXXXX,1010],[0,0]]','2020-11-03T14:49:25'::timestamp,'{}',false,('xxx:xxxx:xxxx::/48'),'null')
backend           | DETAIL:  Key ("timestamp", key)=(2020-11-03 14:49:25, 10227d59d3f1382f68b5b236669cdaa0) already exists.. retrying 1
backend           | db_util - 2020-11-03 17:44:27,048 - INFO @ close: PostgreSQL connection is closed
postgres          | 2020-11-03 17:44:27.061 UTC [8514] ERROR:  duplicate key value violates unique constraint "1_1_bgp_updates_pkey"
postgres          | 2020-11-03 17:44:27.061 UTC [8514] DETAIL:  Key ("timestamp", key)=(2020-11-03 14:49:25, 10227d59d3f1382f68b5b236669cdaa0) already exists.
backend           | db_util - 2020-11-03 17:44:27,061 - ERROR @ execute_values: got error duplicate key value violates unique constraint "1_1_bgp_updates_pkey"
backend           | DETAIL:  Key ("timestamp", key)=(2020-11-03 14:49:25, 10227d59d3f1382f68b5b236669cdaa0) already exists.. retrying 2
postgres          | 2020-11-03 17:44:27.061 UTC [8514] STATEMENT:  INSERT INTO bgp_updates (prefix, key, origin_as, peer_asn, as_path, service, type, communities, timestamp, hijack_key, handled, matched_prefix, orig_path) VALUES ('xxx:xxxx:xxxx::/48','10227d59d3f1382f68b5b236669cdaa0',XXXXX,XXXXX,ARRAY[XXXXX,XXXXX,XXXXX,XXXXX],'bgpstreamlive|ris|rrc21','A','[[XXXXX,1010],[0,0]]','2020-11-03T14:49:25'::timestamp,'{}',false,('xxx:xxxx:xxxx::/48'),'null')
backend           | db_util - 2020-11-03 17:44:28,063 - INFO @ close: PostgreSQL connection is closed
postgres          | 2020-11-03 17:44:28.075 UTC [8515] ERROR:  duplicate key value violates unique constraint "1_1_bgp_updates_pkey"
postgres          | 2020-11-03 17:44:28.075 UTC [8515] DETAIL:  Key ("timestamp", key)=(2020-11-03 14:49:25, 10227d59d3f1382f68b5b236669cdaa0) already exists.
postgres          | 2020-11-03 17:44:28.075 UTC [8515] STATEMENT:  INSERT INTO bgp_updates (prefix, key, origin_as, peer_asn, as_path, service, type, communities, timestamp, hijack_key, handled, matched_prefix, orig_path) VALUES ('xxx:xxxx:xxxx::/48','10227d59d3f1382f68b5b236669cdaa0',XXXXX,XXXXX,ARRAY[XXXXX,XXXXX,XXXXX,XXXXX],'bgpstreamlive|ris|rrc21','A','[[XXXXX,1010],[0,0]]','2020-11-03T14:49:25'::timestamp,'{}',false,('xxx:xxxx:xxxx::/48'),'null')
backend           | db_util - 2020-11-03 17:44:28,075 - ERROR @ execute_values: got error duplicate key value violates unique constraint "1_1_bgp_updates_pkey"
backend           | DETAIL:  Key ("timestamp", key)=(2020-11-03 14:49:25, 10227d59d3f1382f68b5b236669cdaa0) already exists.. retrying 3
backend           | db_util - 2020-11-03 17:44:29,077 - INFO @ close: PostgreSQL connection is closed
postgres          | 2020-11-03 17:44:29.089 UTC [8516] ERROR:  duplicate key value violates unique constraint "1_1_bgp_updates_pkey"
postgres          | 2020-11-03 17:44:29.089 UTC [8516] DETAIL:  Key ("timestamp", key)=(2020-11-03 14:49:25, 10227d59d3f1382f68b5b236669cdaa0) already exists.
postgres          | 2020-11-03 17:44:29.089 UTC [8516] STATEMENT:  INSERT INTO bgp_updates (prefix, key, origin_as, peer_asn, as_path, service, type, communities, timestamp, hijack_key, handled, matched_prefix, orig_path) VALUES ('xxx:xxxx:xxxx::/48','10227d59d3f1382f68b5b236669cdaa0',XXXXX,XXXXX,ARRAY[XXXXX,XXXXX,XXXXX,XXXXX],'bgpstreamlive|ris|rrc21','A','[[XXXXX,1010],[0,0]]','2020-11-03T14:49:25'::timestamp,'{}',false,('xxx:xxxx:xxxx::/48'),'null')
backend           | db_util - 2020-11-03 17:44:29,090 - ERROR @ execute_values: got error duplicate key value violates unique constraint "1_1_bgp_updates_pkey"
backend           | DETAIL:  Key ("timestamp", key)=(2020-11-03 14:49:25, 10227d59d3f1382f68b5b236669cdaa0) already exists.. retrying 4
backend           | db_util - 2020-11-03 17:44:30,091 - INFO @ close: PostgreSQL connection is closed
postgres          | 2020-11-03 17:44:30.104 UTC [8517] ERROR:  duplicate key value violates unique constraint "1_1_bgp_updates_pkey"
postgres          | 2020-11-03 17:44:30.104 UTC [8517] DETAIL:  Key ("timestamp", key)=(2020-11-03 14:49:25, 10227d59d3f1382f68b5b236669cdaa0) already exists.
postgres          | 2020-11-03 17:44:30.104 UTC [8517] STATEMENT:  INSERT INTO bgp_updates (prefix, key, origin_as, peer_asn, as_path, service, type, communities, timestamp, hijack_key, handled, matched_prefix, orig_path) VALUES ('xxx:xxxx:xxxx::/48','10227d59d3f1382f68b5b236669cdaa0',XXXXX,XXXXX,ARRAY[XXXXX,XXXXX,XXXXX,XXXXX],'bgpstreamlive|ris|rrc21','A','[[XXXXX,1010],[0,0]]','2020-11-03T14:49:25'::timestamp,'{}',false,('xxx:xxxx:xxxx::/48'),'null')
backend           | db_util - 2020-11-03 17:44:30,104 - ERROR @ execute_values: got error duplicate key value violates unique constraint "1_1_bgp_updates_pkey"
backend           | DETAIL:  Key ("timestamp", key)=(2020-11-03 14:49:25, 10227d59d3f1382f68b5b236669cdaa0) already exists.. retrying 5
backend           | db_util - 2020-11-03 17:44:31,106 - INFO @ close: PostgreSQL connection is closed
postgres          | 2020-11-03 17:44:31.118 UTC [8518] ERROR:  duplicate key value violates unique constraint "1_1_bgp_updates_pkey"
postgres          | 2020-11-03 17:44:31.118 UTC [8518] DETAIL:  Key ("timestamp", key)=(2020-11-03 14:49:25, 10227d59d3f1382f68b5b236669cdaa0) already exists.
postgres          | 2020-11-03 17:44:31.118 UTC [8518] STATEMENT:  INSERT INTO bgp_updates (prefix, key, origin_as, peer_asn, as_path, service, type, communities, timestamp, hijack_key, handled, matched_prefix, orig_path) VALUES ('xxx:xxxx:xxxx::/48','10227d59d3f1382f68b5b236669cdaa0',XXXXX,XXXXX,ARRAY[XXXXX,XXXXX,XXXXX,XXXXX],'bgpstreamlive|ris|rrc21','A','[[XXXXX,1010],[0,0]]','2020-11-03T14:49:25'::timestamp,'{}',false,('xxx:xxxx:xxxx::/48'),'null')
backend           | messaging - 2020-11-03 17:44:31,118 - ERROR @ _receive_callback: exception
backend           | Traceback (most recent call last):
backend           |   File "/usr/local/lib/pyenv/versions/3.6.8/lib/python3.6/site-packages/artemis_utils/db_util.py", line 145, in execute_values
backend           |     self._cursor, query, vals, page_size=page_size
backend           |   File "/usr/local/lib/pyenv/versions/3.6.8/lib/python3.6/site-packages/psycopg2/extras.py", line 1281, in execute_values
backend           |     cur.execute(b''.join(parts))
backend           | psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "1_1_bgp_updates_pkey"
backend           | DETAIL:  Key ("timestamp", key)=(2020-11-03 14:49:25, 10227d59d3f1382f68b5b236669cdaa0) already exists.
backend           | During handling of the above exception, another exception occurred:
backend           | Traceback (most recent call last):
backend           |   File "/usr/local/lib/pyenv/versions/3.6.8/lib/python3.6/site-packages/artemis_utils/db_util.py", line 145, in execute_values
backend           |     self._cursor, query, vals, page_size=page_size
backend           |   File "/usr/local/lib/pyenv/versions/3.6.8/lib/python3.6/site-packages/psycopg2/extras.py", line 1281, in execute_values
backend           |     cur.execute(b''.join(parts))
backend           | psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "1_1_bgp_updates_pkey"
backend           | DETAIL:  Key ("timestamp", key)=(2020-11-03 14:49:25, 10227d59d3f1382f68b5b236669cdaa0) already exists.
backend           | During handling of the above exception, another exception occurred:
backend           | Traceback (most recent call last):
backend           |   File "/usr/local/lib/pyenv/versions/3.6.8/lib/python3.6/site-packages/artemis_utils/db_util.py", line 145, in execute_values
backend           |     self._cursor, query, vals, page_size=page_size
backend           |   File "/usr/local/lib/pyenv/versions/3.6.8/lib/python3.6/site-packages/psycopg2/extras.py", line 1281, in execute_values
backend           |     cur.execute(b''.join(parts))
backend           | psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "1_1_bgp_updates_pkey"
backend           | DETAIL:  Key ("timestamp", key)=(2020-11-03 14:49:25, 10227d59d3f1382f68b5b236669cdaa0) already exists.
backend           | During handling of the above exception, another exception occurred:
backend           | Traceback (most recent call last):
backend           |   File "/usr/local/lib/pyenv/versions/3.6.8/lib/python3.6/site-packages/artemis_utils/db_util.py", line 145, in execute_values
backend           |     self._cursor, query, vals, page_size=page_size
backend           |   File "/usr/local/lib/pyenv/versions/3.6.8/lib/python3.6/site-packages/psycopg2/extras.py", line 1281, in execute_values
backend           |     cur.execute(b''.join(parts))
backend           | psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "1_1_bgp_updates_pkey"
backend           | DETAIL:  Key ("timestamp", key)=(2020-11-03 14:49:25, 10227d59d3f1382f68b5b236669cdaa0) already exists.
backend           | During handling of the above exception, another exception occurred:
backend           | Traceback (most recent call last):
backend           |   File "/usr/local/lib/pyenv/versions/3.6.8/lib/python3.6/site-packages/artemis_utils/db_util.py", line 145, in execute_values
backend           |     self._cursor, query, vals, page_size=page_size
backend           |   File "/usr/local/lib/pyenv/versions/3.6.8/lib/python3.6/site-packages/psycopg2/extras.py", line 1281, in execute_values
backend           |     cur.execute(b''.join(parts))
backend           | psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "1_1_bgp_updates_pkey"
backend           | DETAIL:  Key ("timestamp", key)=(2020-11-03 14:49:25, 10227d59d3f1382f68b5b236669cdaa0) already exists.
backend           | During handling of the above exception, another exception occurred:
backend           | Traceback (most recent call last):
backend           |   File "core/database.py", line 1247, in core.database.Worker._insert_bgp_updates
backend           |   File "/usr/local/lib/pyenv/versions/3.6.8/lib/python3.6/site-packages/artemis_utils/db_util.py", line 157, in execute_values
backend           |     self.execute_values(query, vals, page_size, retry_counter)
backend           |   File "/usr/local/lib/pyenv/versions/3.6.8/lib/python3.6/site-packages/artemis_utils/db_util.py", line 157, in execute_values
backend           |     self.execute_values(query, vals, page_size, retry_counter)
backend           |   File "/usr/local/lib/pyenv/versions/3.6.8/lib/python3.6/site-packages/artemis_utils/db_util.py", line 157, in execute_values
backend           |     self.execute_values(query, vals, page_size, retry_counter)
backend           |   [Previous line repeated 2 more times]
backend           |   File "/usr/local/lib/pyenv/versions/3.6.8/lib/python3.6/site-packages/artemis_utils/db_util.py", line 150, in execute_values
backend           |     raise error
backend           |   File "/usr/local/lib/pyenv/versions/3.6.8/lib/python3.6/site-packages/artemis_utils/db_util.py", line 145, in execute_values
backend           |     self._cursor, query, vals, page_size=page_size
backend           |   File "/usr/local/lib/pyenv/versions/3.6.8/lib/python3.6/site-packages/psycopg2/extras.py", line 1281, in execute_values
backend           |     cur.execute(b''.join(parts))
postgres          | 2020-11-03 17:44:31.120 UTC [8518] ERROR:  current transaction is aborted, commands ignored until end of transaction block`

**Comment by vkotronis** [comment]
I think I know what went wrong here. The DB took so much time to initialize that old updates were delivered. I will add an extra check to make sure this never happens.
Will solve in PR #472

**Comment by vkotronis** [comment]
Closed by #472
