### ISSUE TITLE
Migration steps when changing directory of Artemis

### ISSUE THREAD

**Issue by turbo-david** [FORTH-ICS-INSPIRE/artemis#474]
If you need to move the location of Artemis due to perms etc.
Please have a writeup of what needs to be moved.

IE. User DB, Local Configs, .env files, Docker compose files.

**Comment by vkotronis** [comment]
Closed by https://github.com/FORTH-ICS-INSPIRE/artemis/commit/b213f45fd89c873120bcdc5fca1ddeebe9665679
