### ISSUE TITLE
Add documentation on how to expose Postgress so you can use your own Grafana instance

### ISSUE THREAD

**Issue by turbo-david** [FORTH-ICS-INSPIRE/artemis#475]
We run our own Grafana instance and want to be able to hit Postgress directly on docker.

I was able to update the docker-compose.yaml to have the ports show up on the actual host.

Updates below.

postgres:
        image: timescale/timescaledb:1.1.0-pg10
        container_name: postgres
        restart: always
        networks:
            - artemis
        ports:
            - "5432:5432"

Could this info be added to the Grafana documenation.

Thanks

**Comment by vkotronis** [comment]
Closed by https://github.com/FORTH-ICS-INSPIRE/artemis/commit/b88ddbd5c02fa4d6db2ba1cee504e75733261c19
