### ISSUE TITLE
Logging config uses depreciated class

### ISSUE THREAD

**Issue by turbo-david** [FORTH-ICS-INSPIRE/artemis#476]
The current documenation: https://bgpartemis.readthedocs.io/en/latest/loggingconf/ states to use the following class for smtps_handler

# utils.TLSSMTPHandler for TLS
# utils.SSLSMTPHandler for SSL
class: utils.TLSSMTPHandler

It appears the class name was changed to artemis_utils.TLSSMTPHandler per: https://github.com/FORTH-ICS-INSPIRE/artemis/blob/master/utils/artemis_utils/__init__.py#L121

Can we get the logging documentation updated to accommodate for the change.

Thanks

**Comment by vkotronis** [comment]
Closed by https://github.com/FORTH-ICS-INSPIRE/artemis/commit/eaa08b8c874f723b3ad05bc839a933605b4b6a19
