### ISSUE TITLE
Allow for minor config changes, without reloading prefixes

### ISSUE THREAD

**Issue by pixitha** [FORTH-ICS-INSPIRE/artemis#480]
**Is your feature request related to a problem? Please describe.**
Currently if you update any part of the config, such as commenting out a monitor, like RIPE or routeviews, it reloads all of the prefixes into the monitors/detectors.

**Describe the solution you'd like**
It would be nice if the config ingestion system was smart enough to ignore reloading the database/prefixes for changes that don't need it to be reloaded.

**Describe alternatives you've considered**
Changes to monitors not requiring a full reload, also changes to ASN sets?

**Additional context**
On a system with a number of prefixes, there is a significant delay in monitoring on every save to the config file.

**Comment by vkotronis** [comment]
I will work on this on ongoing PR https://github.com/FORTH-ICS-INSPIRE/artemis/pull/472 to add per-section hashes (prefixes, monitors, autoignore, asns, rules). If the prefixes/asns/rules do not change, no need to reload any service except for the database (that stores the most recent conf in any case) and conf replicas. If only monitors change, then only the monitor services should be notified. I will test and re-visit the issue.

**Comment by vkotronis** [comment]
Closed by #472
