### ISSUE TITLE
Remove support for TLS 1.0 and 1.1

### ISSUE THREAD

**Issue by racompton** [FORTH-ICS-INSPIRE/artemis#482]
TLS 1.0 and 1.1 should be removed for security reasons.  Add in 'ssl_protocols TLSv1.2 TLSv1.3;' into the server section of frontend/nginx.conf

**Comment by vkotronis** [comment]
https://www.cyberciti.biz/faq/configure-nginx-to-use-only-tls-1-2-and-1-3/
Will open a PR for this to edit the default nginx.conf, however this is configurable by the user as a local config file.
https://www.cyberciti.biz/faq/configure-nginx-to-use-only-tls-1-2-and-1-3/
