### ISSUE TITLE
Configurable web ui timeout

### ISSUE THREAD

**Issue by racompton** [FORTH-ICS-INSPIRE/artemis#486]
Have a variable in .env or webapp.cfg to define idle timeout.

**Comment by vkotronis** [comment]
Will address after releasing new frontend, since there will be a lot of changes in the new one. Will keep issue open and address post-release.

**Comment by vkotronis** [comment]
Addressed in new frontend (to be released): https://github.com/FORTH-ICS-INSPIRE/artemis-web
