### ISSUE TITLE
two rows of tables vs. two columns of tables for GUI layout?

### ISSUE THREAD

**Issue by pixitha** [FORTH-ICS-INSPIRE/artemis#497]
**Is your feature request related to a problem? Please describe.**
With the larger list of micro-services on right side of the page now, its difficult to have a large enough view for this layout to be useful anymore. I had to shrink my chrome view to 67% to make it useful for a single pane of information, but even then your still losing a bunch of info from the main view.

**Describe the solution you'd like**
It might be easier to change from the two column view currently in use, to a set of 2 rows instead, moving the data to a more horizontal view. This also makes more sense due to the wide screen nature of most monitors. I think it might be a good idea to move a different status icon as well, that is smaller and isn't necessarily a toggle switch (since the dashboard doesn't affect turning anything on). The activity box seems less useful, maybe make it a banner message at the top of the page that goes away? or maybe just text that shows to the left of the "Admin" button in the top bar? Having the stats up near the top is useful for keeping track of unhandled updates etc.

**Describe alternatives you've considered**
Other alternatives could be using much smaller buttons to display status, to fit more on screen.

**Additional context**
Normal zoom on Chrome, on a Macbook@15.4-inch (2880 x 1800)
<img width="1680" alt="Screen Shot 2020-12-22 at 4 36 28 PM" src="https://user-images.githubusercontent.com/503771/103020096-e2679100-4515-11eb-9bec-44bcf232a041.png">

67% zoom
<img width="1668" alt="Screen Shot 2020-12-22 at 4 40 09 PM" src="https://user-images.githubusercontent.com/503771/103020193-fca16f00-4515-11eb-9296-7c5ab5d50b57.png">

**Comment by vkotronis** [comment]
Addressed in new frontend (to be released): https://github.com/FORTH-ICS-INSPIRE/artemis-web
