### ISSUE TITLE
UI issues

### ISSUE THREAD

**Issue by pgigis** [FORTH-ICS-INSPIRE/artemis#56]
**Describe the bug**

- Change Hijack AS to Hijacker AS
- Fix indentation on hijacks table
- Make more clear the buttons of navbar
- Change Timewindow phrase on BGP Updates, Hijacks tables and fix bug with custom window.
- Change Hijack tags.

**Affected Component(s)**
- [ ] Back-End (Database, Microservices, Containers, etc)
- [X] Front-End (Flask, API, etc)
- [ ] Docs
- [ ] Build System

**To Reproduce**

**Expected behavior**

**Screenshots**

**System (please complete the following information):**

**Additional context**

**Comment by vkotronis** [comment]
Closed by https://github.com/FORTH-ICS-INSPIRE/artemis/pull/59
