### ISSUE TITLE
Failed DB query

### ISSUE THREAD

**Issue by slowr** [FORTH-ICS-INSPIRE/artemis#57]
**Describe the bug**
Something causes a query to fail when updating a hijack. Exception suggests that the values are empty but I think this should never happen.

**Affected Component(s)**
- [x] Back-End (Database, Microservices, Containers, etc)
- [ ] Front-End (Flask, API, etc)
- [ ] Docs
- [ ] Build System

**To Reproduce**
Unknown behavior. Observed when monitorint /0 prefix.

**Expected behavior**
No exception and normal handling of the update/hijack.

**Screenshots**
![image](https://user-images.githubusercontent.com/3428023/52347179-00af6b00-2a2a-11e9-8488-39544ba24115.png)

**System (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by vkotronis** [comment]
@slowr is this fixed in your latest PR? If yes, please connect it by mentioning it here (and close after the PR is merged).
