### ISSUE TITLE
Ability to suppress logs from bgpstreamlivetap_1 container (or others)

### ISSUE THREAD

**Issue by pixitha** [FORTH-ICS-INSPIRE/artemis#578]
**Is your feature request related to a problem? Please describe.**
The logs for invalid messages are very spammy and filling up the docker-compose logs esp if your looking back over a period of days. It would be nice to not have the logs at all, if they are not really useful.

`bgpstreamlivetap_1   | process - 2021-03-20 17:25:44,039 - WARNING @ run: Invalid format message: {'type': 'A', 'timestamp': 1616255663.0, 'path': ['####', '####', '####'], 'service': 'bgpstreamlive|routeviews|route-views.sg', 'communities': [{'asn': ####, 'value': 100}, {'asn': ####, 'value': 4}, {'asn': ####, 'value': 21000}, {'asn': ####, 'value': 204}, {'asn': ####, 'value': 10101}, {'asn': ####, 'value': 22013}, {'asn': ####, 'value': 10100}, {'asn': ####, 'value': 1051}, {'asn': ####, 'value': 1000}], 'prefix': 'xxx.xxx.xxx.xxx', 'peer_asn': ####}`

**Describe the solution you'd like**
Can we look at getting the maintainer to lower the classification of some types of messages away from warning, to info? Then we could filter out all of the info and such?

**Describe alternatives you've considered**
Things that Artemis deems unimportant, should be filtered it possible.

**Comment by vkotronis** [comment]
Fixed via https://github.com/FORTH-ICS-INSPIRE/artemis/commit/8c69eb898046ab8470755042ede7a0eae79c2a2e
You can pull the latest master containers and code (requires ARTEMIS shutdown and start, as usual)
