### ISSUE TITLE
Version is not showing in the webUI

### ISSUE THREAD

**Issue by racompton** [FORTH-ICS-INSPIRE/artemis#591]
The version is not showing at the bottom left of the page.  It shows:

ARTEMIS v.'latest@HEAD'
 
Not sure if this a bug.  I thought it should say something like: ARTEMIS v.2.0.0

**Comment by vkotronis** [comment]
The version you see is normal. You set the version to "latest" (first part of the version) and the "HEAD" is stemming from git itself since you downloaded the latest git code. So the string you see is correct. Resolving.
