### ISSUE TITLE
Admin Login Bug

### ISSUE THREAD

**Issue by tobpip** [FORTH-ICS-INSPIRE/artemis#600]
**Describe the bug**
When logging in via the Web GUI, the login data is not accepted. Direct access via the URL https://IP_address /overview is also not possible.

Solution: By using the "Remember Me" function when logging in, this works again. 

**Affected Component(s)**
- [ ] Back-End (Database, Microservices, Containers, etc)
- [x] Front-End (Flask, API, etc)
- [ ] Docs
- [ ] Build System

**To Reproduce**
Artemis Version 2.0.0 

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
 - OS: [Windows]
 - Browser [chrome -  91.0.4472.77]
 - Version [ 91.0.4472.77 ]
 - Artemis run on an Ubuntu 18.04.5 LTS container

**Additional context**

**Comment by vkotronis** [comment]
To be taken up in https://github.com/FORTH-ICS-INSPIRE/artemis-web/issues/100 by frontend dev

**Comment by vkotronis** [comment]
This does not apply in newest release 2.1.0 as well in the `latest` ARTEMIS version. If you still encounter the issue with the new frontend, please re-open.
