### ISSUE TITLE
Fix LDAP in frontend and update env and docs

### ISSUE THREAD

**Issue by smith8917** [FORTH-ICS-INSPIRE/artemis#601]
**Describe the bug**
Hardcoded variables in LDAP config, lines 13 and 14 here:
https://github.com/FORTH-ICS-INSPIRE/artemis-web/blob/d005e931de866d47800355d69d6f0bea353cb2e4/apps/artemis-web/libs/passport-strategies/ldap-strategy.ts

**Affected Component(s)**
- [x ] Back-End (Database, Microservices, Containers, etc)
- [ ] Front-End (Flask, API, etc)
- [ ] Docs
- [ ] Build System

**Expected behavior**
no hardcoded entries in .env LDAP variables

**Comment by vkotronis** [comment]
child frontend-specific issue created in the correct repo: https://github.com/FORTH-ICS-INSPIRE/artemis-web/issues/101
Any other conf changes that may be required will also take place in master ARTEMIS repo.

**Comment by vkotronis** [comment]
TODO:
[ ] New `.env` vars 
`LDAP_GROUP_SEARCH_BASE="ou=people,dc=planetexpress,dc=com"`
`LDAP_GROUP_SEARCH_FILTER="(member={{dn}})"`
`LDAP_GROUP_SEARCH_ATTRIBUTES="mail,uid"`
[ ] Remove `.env.` var `LDAP_USER_GROUP`
[ ] Update LDAP-related docs (`ldapconf.md`)
[ ] Update `docker-compose` (also in `vagrant`) and `k8s` (`values`, `configmap`,  `frontend-deployment`) vars
