### ISSUE TITLE
Support base_dir option to artemis web

### ISSUE THREAD

**Issue by a16** [FORTH-ICS-INSPIRE/artemis#606]
**Is your feature request related to a problem? Please describe.**
We can access artemis web(frontend) with host based routing (ex. https://artemis.example.com)
I'd be happy if I could access it with path based routing (ex. https://www.example.com/artemis)
I believe it's useful when using http reverse proxy. 

**Describe the solution you'd like**
Add new parameter ARTEMIS_WEB_BASE_DIR. and need to implement something to frontend.

```
ARTEMIS_WEB_HOST=www.examle.com
ARTEMIS_WEB_BASE_DIR=/artemis
```

**Comment by vkotronis** [comment]
Solved by https://github.com/FORTH-ICS-INSPIRE/artemis-web/pull/127 and https://github.com/FORTH-ICS-INSPIRE/artemis/commit/0c2c9f12515eaa22920e92148b9994793a6eb2f3 in `latest`
