### ISSUE TITLE
hijack.log URI broken

### ISSUE THREAD

**Issue by smith8917** [FORTH-ICS-INSPIRE/artemis#613]
Hello!

It looks like the URL that comes through in the alerting module for hijack.log file has a bug in it.  It has `/main` in the URI which, if removed, allows you to reach the specific hijack… but _with_ the `/main` it sends back a 404.

Broken (found in the JSON output in hijack.log):
https://artemis.es.net/main/hijack?key=09d4491693dbee9bae37a63c759ff714
Works (should be in hijack.log):
https://artemis.es.net/hijack?key=09d4491693dbee9bae37a63c759ff714

**Comment by vkotronis** [comment]
located the issue here: https://github.com/FORTH-ICS-INSPIRE/artemis/blob/5b12a9d79a2785d53182244b2eec0d30f87aad96/utils/artemis_utils/logaux.py#L90

Will update the package with a new PR to take care of it, good catch.
