### ISSUE TITLE
Unable to activate microservices in microk8s cluster

### ISSUE THREAD

**Issue by Surphix** [FORTH-ICS-INSPIRE/artemis#620]
**Describe the bug**

Unable to start any of the micro services within kubernetes microk8s cluster. Pods appear to be running and identified in the front end, however toggling micro services on within the admin -> system page does not work.

**Affected Component(s)**
- [X] Back-End (Database, Micro services, Containers, etc)
- [ ] Front-End (Flask, API, etc)
- [ ] Docs
- [ ] Build System

**To Reproduce**
1. Go to 'Admin -> System page'
2. Click on 'Attempt to enable one of the bgp micro services'
3. Nothing occurs, micro service remains in-active

**Expected behavior**
Micro service enables and feed begins to ingest

**Screenshots**
![image](https://user-images.githubusercontent.com/8021518/150018975-e52503d6-a9ac-436f-9a5b-3695845ff57f.png)
![image](https://user-images.githubusercontent.com/8021518/150019303-dafb23a6-1518-409f-8300-a8311c85ed46.png)
![image](https://user-images.githubusercontent.com/8021518/150019414-2747646e-689f-4f73-be0f-007dbdc8b601.png)

**System (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Firefox
 - Version 94.0.2

**Additional context**
Logs do not show any errors related to starting the micro services.

**Comment by vkotronis** [comment]
@Surphix have you tried enabling the `detection` service to see if that works? Also, have you properly configured RIPE RIS in the conf file? If not configured, the base service is running but it does not actually consume data (and appears off in the UI). Note that in general unconfigured monitor microservices appear as off until they are both configured and enabled in the UI.

@CuriouzK0d3r do you have a local deployment to check if e.g., `detection` or `mitigation` services can be properly enabled and run? The `autostarter` microservice is the one that takes care of enabling/disabling the actual service workers of other services: https://github.com/FORTH-ICS-INSPIRE/artemis/blob/5b12a9d79a2785d53182244b2eec0d30f87aad96/backend-services/autostarter/core/autostarter.py#L262

**Comment by vkotronis** [comment]
@Surphix saw that the issue is closed, was it a missing configuration problem? Did you active the microservices after enabling them on the conf file?

**Comment by Surphix** [comment]
@vkotronis I uninstalled and reinstalled the chart, updated the config and it seemed to work after that. Thanks!

**Comment by vkotronis** [comment]
> @vkotronis I uninstalled and reinstalled the chart, updated the config and it seemed to work after that. Thanks!

Great, thanks for reporting this @Surphix and I am glad that it works as expected.
