### ISSUE TITLE
Use with proxy

### ISSUE THREAD

**Issue by Sivolen** [FORTH-ICS-INSPIRE/artemis#627]
Hey! It would be great to implement the ability for Artemis to receive updates through a proxy.

**Comment by vkotronis** [comment]
@Sivolen could you elaborate on this issue? Could you give an example of the arch you have in mind? Currently we get updates from RIPE RIS Live, RouteViews, private Kafka BMP feeds via BGPStream, historical updates via BGPStream and local routes via ExaBGP.

**Comment by vkotronis** [comment]
What would be the proxy interface in your setup? BGP, WebSocket, sth else?

**Comment by Sivolen** [comment]
Hey!
Interested in WebSocket, is it possible to somehow redirect requests to RIPE RIS Live, RouteViews through a proxy?

**Comment by vkotronis** [comment]
@Sivolen I assume yes, if it is not supported out of the box feel free to open PR for new microservice or configuration primitive
