### ISSUE TITLE
pg-amqp-bridge docker image

### ISSUE THREAD

**Issue by CuriouzK0d3r** [FORTH-ICS-INSPIRE/artemis#629]
**Describe the bug**

subzerocloud/pg-amqp-bridge docker image does not exists anymore. We need to either replace it or build it from source.

**Affected Component(s)**
- [x] Back-End (Database, Microservices, Containers, etc)
- [ ] Front-End (Flask, API, etc)
- [ ] Docs
- [ ] Build System

**To Reproduce**

**Expected behavior**

**Screenshots**

**System (please complete the following information):**

**Additional context**

**Comment by vkotronis** [comment]
@CuriouzK0d3r could you check this with high priority? Does it mean that currently we cannot download this? If possible please issue a PR to replace it (hope the new image does not break sth, check also env vars and tests should pass)

**Comment by vkotronis** [comment]
Substituted by https://hub.docker.com/r/curiouzk0d3r/pg-amqp-bridge
