### ISSUE TITLE
Disk full after some time

### ISSUE THREAD

**Issue by Sivolen** [FORTH-ICS-INSPIRE/artemis#654]
**Describe the bug**
Disk full even though disk cleanup option is enabled DB_AUTOCLEAN=24

a.gridnev@pso-artemis-01:~$ df -h
Filesystem                         Size  Used Avail Use% Mounted on
udev                               2.9G     0  2.9G   0% /dev
tmpfs                              595M  2.6M  592M   1% /run
/dev/mapper/ubuntu--vg-ubuntu--lv   97G   93G     0 100% /
tmpfs                              3.0G     0  3.0G   0% /dev/shm
tmpfs                              5.0M     0  5.0M   0% /run/lock
tmpfs                              3.0G     0  3.0G   0% /sys/fs/cgroup
/dev/loop0                          62M   62M     0 100% /snap/core20/1494
/dev/loop1                          62M   62M     0 100% /snap/core20/1518
/dev/loop2                          68M   68M     0 100% /snap/lxd/21835
/dev/sda2                          1.5G  209M  1.2G  16% /boot
/dev/loop3                          45M   45M     0 100% /snap/snapd/15904
/dev/loop4                          47M   47M     0 100% /snap/snapd/16010
/dev/loop5                          68M   68M     0 100% /snap/lxd/22753
tmpfs                              595M     0  595M   0% /run/user/1001

**Affected Component(s)**
- [x] Back-End (Database, Microservices, Containers, etc)
- [ ] Front-End (Flask, API, etc)
- [ ] Docs
- [ ] Build System

**To Reproduce**
1. Running artemis
2. Wait some time
3. A clear and concise description of what you expected to happen.

**System (please complete the following information):**
ubuntu 20.04

**Comment by vkotronis** [comment]
@Sivolen please use a larger disk. We have sample requirements in docs: https://bgpartemis.readthedocs.io/en/latest/requirements/
Please use at least 50Gig and let us know if there is any capacity overloading.
A few gigs is barely sufficient for the OS on top of which the ARTEMIS docker mservices are running.

**Comment by Sivolen** [comment]
> @Sivolen please use a larger disk. We have sample requirements in docs: https://bgpartemis.readthedocs.io/en/latest/requirements/ Please use at least 50Gig and let us know if there is any capacity overloading. A few gigs is barely sufficient for the OS on top of which the ARTEMIS docker mservices are running.

Increased the size to 150 GB let's see how it will be
