### ISSUE TITLE
Document use of workflow to access and use ARTEMIS APIs

### ISSUE THREAD

**Issue by vkotronis** [FORTH-ICS-INSPIRE/artemis#68]
**Is your feature request related to a problem? Please describe.**
Workflow to access and use ARTEMIS APIs is not documented.

**Describe the solution you'd like**
Document use of workflow to access and use ARTEMIS APIs in the wiki (dedicated page)
You can use: https://github.com/FORTH-ICS-INSPIRE/artemis/wiki/Graphql-API

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by slowr** [comment]
Documented on wiki
