### ISSUE TITLE
Unable to docker-compose up

### ISSUE THREAD

**Issue by jalewis** [FORTH-ICS-INSPIRE/artemis#7]
**Describe the bug**
I get the following error when running docker-compose up.

Pulling backend (inspiregroup/artemis-backend:release-1.0.0)...
release-1.0.0: Pulling from inspiregroup/artemis-backend
54f7e8ac135a: Pull complete
d6341e30912f: Pull complete
087a57faf949: Pull complete
5d71636fb824: Pull complete
0c1db9598990: Pull complete
2eeb5ce9b924: Pull complete
a8c530378055: Pull complete
687ed2fb2a0d: Pull complete
620aea26e853: Pull complete
d1f69edf51b4: Pull complete
d521975a68ff: Pull complete
d6bfccd2c905: Pull complete
4ae245b6935d: Pull complete
58a72a140d62: Pull complete
7490874e1599: Pull complete
60c0048962c3: Extracting [==================================================>]  767.5kB/767.5kB
64bea18216f5: Download complete
2c8b54a5a101: Download complete
de349e122938: Download complete
04968a44e8f8: Download complete
c7f9972b77fa: Download complete
78c5c5662f4a: Download complete
c62301620d19: Download complete
b57b1a7f21cd: Download complete
9ea41fa60b16: Download complete
5ab8a96196e4: Download complete
960687b25614: Download complete
edf4a9369020: Download complete
ERROR: failed to register layer: ApplyLayer exit status 1 stdout:  stderr: lchown /root/src/wandio-1.0.4: invalid argument

**Affected Component(s)**
- [ ] Back-End (Database, Microservices, Containers, etc)
- [ ] Front-End (Flask, API, etc)
- [ ] Docs
- [x] Build System

**To Reproduce**
1. run docker-compose up -d

**Expected behavior**
I expect the images to build.

**Screenshots**

**System (please complete the following information):**
 - OS: ubuntu 18.04
# docker-compose --version
docker-compose version 1.20.0, build ca8d3c6
# docker -v
Docker version 18.09.0, build 4d60db4

**Additional context**

**Comment by slowr** [comment]
Hi @jalewis and thank you for reaching out.

I managed to run artemis without any problem with the same versions of docker and docker-compose that you have on Ubuntu 18.04.

If I have to guess, you might have non-root permissions on the user to use docker or maybe your setup is corrupted and you might need to clean up the docker images that you have pulled (`docker system prune`)

**Comment by vkotronis** [comment]
@jalewis any news on this bug in your installation? We were not able to replicate it. For detailed instructions, in case you still face problems with installation, please let us know on our [discord server](https://discord.gg/8UerJvh) as @slowr advises.

**Comment by vkotronis** [comment]
Closing as non-replicable. @jalewis please feel free to reopen if you still encounter issues with building.
