### ISSUE TITLE
Sort BGP hijacks based on their last updated time field

### ISSUE THREAD

**Issue by vkotronis** [FORTH-ICS-INSPIRE/artemis#71]
**Is your feature request related to a problem? Please describe.**
Right now hijacks are sorted based on their detection timestamp (time_detected).

**Describe the solution you'd like**
Hijacks should be sorted based on their time_last field. The time selection (24h, etc.) should also be based on this field from now on. The appropriate index should also be added to the db (migration required).

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by slowr** [comment]
this means that we need to change the unique index in timescale's hypertable though. right?
