### ISSUE TITLE
Expand/Collapse field in overview for same multiple modules

### ISSUE THREAD

**Issue by slowr** [FORTH-ICS-INSPIRE/artemis#75]
**Is your feature request related to a problem? Please describe.**
When we run many instances of the same module the status overview gets really difficult to read.

**Describe the solution you'd like**
We need to group the same instances and expand/collapse them when we want to check their status.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by vkotronis** [comment]
@slowr could you please add some screenshots for context? To understand exactly what should be fixed?

**Comment by slowr** [comment]
Status overview with 10 detectors and database clients.

![image](https://user-images.githubusercontent.com/3428023/53528360-1b897280-3af2-11e9-8579-8b6b133574aa.png)
