### ISSUE TITLE
Enable config format from rfc2622 for prefixes

### ISSUE THREAD

**Issue by pixitha** [FORTH-ICS-INSPIRE/artemis#85]
**Is your feature request related to a problem? Please describe.**
We have a lot of very large subnets, /10s and such, so having to list them as /24s is rough and makes for a huge config file.

**Describe the solution you'd like**
It would be nice to allow the config format to use some operators like what we use with our IRRs (RADB) route-sets. They follow [rfc2622](https://tools.ietf.org/html/rfc2622) which has a few operators, although I'm personally only interested in `^n`.

 ^n where n is an integer, stands for all the length n specifics of
      the address prefix.  For example, 30.0.0.0/8^16 contains all the
      more specifics of 30.0.0.0/8 which are of length 16 such as
      30.9.0.0/16.

**Describe alternatives you've considered**
none, except leaving as is.

**Additional context**
Example:

10.0.0.0/8^24 would match all the /24s in the /8, but only require a tiny config, instead of hundreds of /24s.

**Comment by vkotronis** [comment]
From the RFC:
```
^- is the exclusive more specifics operator; it stands for the more
      specifics of the address prefix excluding the address prefix
      itself.  For example, 128.9.0.0/16^- contains all the more
      specifics of 128.9.0.0/16 excluding 128.9.0.0/16.

   ^+ is the inclusive more specifics operator; it stands for the more
      specifics of the address prefix including the address prefix
      itself.  For example, 5.0.0.0/8^+ contains all the more specifics
      of 5.0.0.0/8 including 5.0.0.0/8.

   ^n where n is an integer, stands for all the length n specifics of
      the address prefix.  For example, 30.0.0.0/8^16 contains all the
      more specifics of 30.0.0.0/8 which are of length 16 such as
      30.9.0.0/16.

   ^n-m where n and m are integers, stands for all the length n to
      length m specifics of the address prefix.  For example,
      30.0.0.0/8^24-32 contains all the more specifics of 30.0.0.0/8
      which are of length 24 to 32 such as 30.9.9.96/28.
```

I will check the configuration logic and update accordingly.
