### ISSUE TITLE
Front End improvements

### ISSUE THREAD

**Issue by pgigis** [FORTH-ICS-INSPIRE/artemis#88]
**Is your feature request related to a problem? Please describe.**
Nope. Its only improvements. 

**Describe the solution you'd like**
1) Add filter by type on hijacks.
2) View hijack by its key.
3) Sort Hijacks using # Peer Seen and # ASes infected. 

**Describe alternatives you've considered**

**Additional context**

**Comment by vkotronis** [comment]
Closed by https://github.com/FORTH-ICS-INSPIRE/artemis/pull/113
