### ISSUE TITLE
No-export support in configuration rules

### ISSUE THREAD

**Issue by slowr** [FORTH-ICS-INSPIRE/artemis#93]
**Is your feature request related to a problem? Please describe.**
Support no-export prefixes

**Describe the solution you'd like**
Add an additional field on the configuration rules to enable no-export functionality

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by vkotronis** [comment]
@slowr please document this more. For example, when we see a no-export prefix being advertised with a path length > 2 (with the path being cleaned first for prepending, loops, etc.), that means that it is is not going to a monitor directly connected to the first-hop neighbor of the origin but is a "route leak".
