### ISSUE TITLE
Check if .env can get out of version control for security reasons

### ISSUE THREAD

**Issue by vkotronis** [FORTH-ICS-INSPIRE/artemis#96]
**Is your feature request related to a problem? Please describe.**
Currently .env is version-controlled, but it contains secrets; accidentally overwriting it by a fresh install vs. accidently pushing to git are risks. Therefore, we need to check how to handle this properly, e.g., pushing this too in local_configs.

**Describe the solution you'd like**
Check a possible solution to the location problem and the writing of secrets on disk.

**Describe alternatives you've considered**
N/A

**Additional context**
https://github.com/docker/compose/issues/6170

**Comment by pixitha** [comment]
Would be nice to move the auth/secrets to another file in local_config perhaps, so there is less risk of overwriting existing values on upgrades/reinstalls.

We also have requirements internally that we are not allowed to check any configs into our internal git server with saved credentials or shared keys. So we will endup storing most of that data in a vault-like remote storage facility and accessing as needed. I think we would access and then write them to the linux environment, then have artemis read from that?

**Comment by slowr** [comment]
unfortunately we can't move the `.env` file to other folder because it is still an ongoing issue to support external .env files in the docker-compose repository
https://github.com/docker/compose/issues/6170

because we have to do with environment variables you can delete the `.env` file and actually import them through another script that is located somewhere else.

**Comment by slowr** [comment]
You can copy the `.env` file to another directory and point to it from inside the docker-compose file.

https://docs.docker.com/compose/environment-variables/
**The “env_file” configuration option**
You can pass multiple environment variables from an external file through to a service’s containers with the ‘env_file’ option, just like with docker run --env-file=FILE ...:

```
web:
  env_file:
    - web-variables.env
```

Closing this issue
